### ISSUE TITLE
Criar model `documents`

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#109]
Um novo modelo, chamado `documents`, foi adicionado no [documento de modelagem do banco de dados](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_1930). Essa issue está relacionada a implementação dele nos models da aplicação.

**Comment by JeanCHilger** [comment]
como discutido em #110, o campo `data` deixará de existir, dando lugar à uma pasta no servidor.
