### ISSUE TITLE
Criar endpoint de api `/documents` para gerenciar o model documents

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#110]
Depende de: #109 

Esse endpoint precisa permitir todas as operações CRUD com o model `documents` (descrito na issue #109). No momento, não precisamos de interface gráfica para gerenciar esse modelo, apenas interações via api.

É importante notar que o campo `data` do modelo `documents` está marcado como `binary`. Não sei como o sqlite modela isso internamente, mas um campo `binary` é aquele onde dados são colocados de forma "binária/bruta". Um exemplo é, por exemplo, o conteúdo de um arquivo de audio.

Logo, o endpoin `/documents` precisa ser capaz de receber informações binárias (como um arquivo inteiro). Talvez receber isso em como `multipart/form-data`. Faz parte dessa issue pesquisar sobre isso no laravel e ver como a comunidade trata isso. Provavelmente já exista um suporte para recebimento de arquivos implementado, pronto e lindo no Laravel esperando para ser usado 😄

**Comment by JeanCHilger** [comment]
Tenho três dúvidas em relação à este modelo/API:

1. O arquivo será armazenado apenas no banco, ou será salvo numa pasta no servidor também?
2. Caso o arquivo seja armazenado apenas no banco: Por que não criar uma pasta no servidor para armazená-lo, e no banco salvar apenas o caminho (peço isto pois sempre utilizei essa abordagem e não conheço muito as diferenças :sob:)?
3. Se o arquivo for armazenado apenas no banco, o que o campo `path` representa?

**Comment by Dovyski** [comment]
Respondendo às dúvidas:

1. Eu fiz a modelagem para permitir ambos (se o campo `path` estiver vazio ou for null, assumimos que o campo `data` contém os dados do arquivo).

As dúvidas 2 e 3 são relacionadas. Eu já usei essas duas abordagens (guardar o arquivo no banco e externamente). Ambas tem prós e contras. Eu acho que, no nosso caso, vale mais a pena colocar os arquivos em uma pasta. Podemos simplificar a modelagem removendo o campo `data` para deixar isso bem claro.

Que tal? Pensando melhor agora (e com as tuas dúvidas), não acho que vale a pena mantermos ambas as implementações. Podemos acabar tendo que lidar com os contras de ambas as abordagens haha

**Comment by JeanCHilger** [comment]
Concordo em utilizar uma pasta, acredito que assim o banco fique mais simples, evitando erros. Acredito que em relação à segurança não haja muita diferença entre as abordagens.

**Comment by Dovyski** [comment]
Até pode ser uma questão de segurança, mas eu tive muito mais problema com performance. Enviar arquivos (especialmente grandes) pelas conexões de banco não é nada otimizado 😛

**Comment by JeanCHilger** [comment]
resolvida em #123
