### ISSUE TITLE
[BUG, Discussão] Too many requests

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#112]
# Problema
Após utilizar o site por um certo tempo, o seguinte erro pode ocorrer:
![image](https://user-images.githubusercontent.com/19687197/92307325-0f466700-ef6c-11ea-8b8e-503a526a2282.png)

# Causa
Isto ocorre pois o laravel possui um limite interno para a quantidade de requisições que podem ser efetuadas em um certo período de tempo.

# Possíveis Soluções
Poderíamos simplesmente remover ou elever este limite até não ocorrer mais este erro, no entanto está abordagem pode resultar em problemas de segurança.

Outra solução (talvez mais segura) seria utilizar um sistema de cache. Todavia esta solução pode não ser o suficiente, visto que cada vez um um novo item é "aberto" novas requisições são feitas. Acredito que esta solução iria sanar apenas alguns casos.

## Algumas discussões sobre o problema:
- StackOverflow: [Disable rate limiter in Laravel?](https://stackoverflow.com/questions/43058219/disable-rate-limiter-in-laravel)
- GitHub/Laravel: [429: Too Many Requests](https://github.com/laravel/framework/discussions/27512)

**Comment by JeanCHilger** [comment]
Com "utilizar o site por um certo tempo" quero dizer: "clicar insanamente até o erro ocorrer". Não é um comportamento que todo usuário irá demonstrar, mas acredito que o problema ainda seja um inconveniente

**Comment by Dovyski** [comment]
Não acho que isso seja um problema tão grave agora. Podemos elevar um limite nesse primeiro momento. Eu acho que o Laravel controla o número de requests por minuto ou algo parecido. O ideal é verificarmos porque estamos atingindo o limite e trabalhar para reduzir isso (talvez centralizar as várias chamadas em um único ponto da API, por exemplo).

**Comment by andrewmsilva** [comment]
Isso ainda tem acontecido? Se não, podemos fechar essa issue por ora.

**Comment by JeanCHilger** [comment]
Acredito que foi "parcialmente resolvido" aumentando o limite de *requests*. Como os dados envolvidos não são tão sensíveis, acredito que possa ser mantido desta forma. E também, algumas refatorações no *backend* e na forma como as requests estão sendo feitas pode ajudar (até mesmo em questões de eficiência).

**Comment by Dovyski** [comment]
Eventualmente vamos separar os projetos e repos próprios como discutimos na reunião. Acho que podemos fechar essa issue por enquanto.

**Comment by JeanCHilger** [comment]
Fechando a issue então.
