### ISSUE TITLE
[BUG] Comentário é adicionado de forma duplicada

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#122]
No ambiente de testes [qa.mural.practice.uffs.cc](https://qa.mural.practice.uffs.cc/), ao adicionar um novo comentário, ele é adicionado de forma duplicada. No banco apenas um é criado, por tanto o _bug_ deve estar em `CommentList`.

**Comment by oraphaBorges** [comment]
Bug corrigido com a remoção de invocação duplicada de comentários
