### ISSUE TITLE
Criar endpoints /login e /logout

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#124]
Uma API deverá ser disponibilizada para o login com o IdUFFS.

### [POST] `/login`
Efetua o *login* de um usuário.
#### *Payload*
- `iduffs`: **`string`**, IdUFFS do usuário (nome.sobrenome);
- `password`: **`string`**, TODO;

#### *Response*
Retorna um JSON com o usuário autenticado (será especificado no documento).

### [GET] `/logout`
Efetua o _logout_ de um usuário.
#### *Query*
- `id`: **`string`**, id do usuário que está logado;

#### *Response*
(vazio)

**NOTA:** O campo `password` deverá ser enviado de forma a não revelar a senha do usuário. A forma como isto será implementado ainda será pensada. Irei marcar o @Dovyski e o @arufonsekun, caso tenham alguma ideia de antemão.

**Comment by JeanCHilger** [comment]
@andrewmsilva, verifique se esta especificação para a API fica de acordo com uma implementação no app. Isto pode ser ajustado para facilitar a implementação no app sem complicações da parte do _banckend_. Qualquer sugestão/modificação necessária, pode comentar aqui mesmo.

**Comment by Dovyski** [comment]
Vamos usar HTTPS para a comunicação, então não precisamos fazer nenhuma criptografia no nosso lado para proteger o password.

Minha única preocupação é o `/logout`. Da forma que está, qualquer um que saiba o idUFFS de alguém (o que é domínio público) consegue deslogar a pessoa do app.

Eu sugiro criarmos um modelo chamado `Sessions` com o seguinte:

```php
Schema::create('sessions', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->foreignId('user_id');
    $table->string('token', 60); // usar como valor depois: hash('sha256', Str::random(60));
    $table->string('device', 250);
    $table->timestamps();

   $table->foreign('user_id')->references('id')->on('users');
});
```

Na chamada ao `/login`, se o usuário é válido, inserimos uma entrada em `sessions`, colocando em `device` o `User Agent` do browser (se vier do mobile, saberemos que dispositivo é). O `/login` retorna as infos retornadas pelo `AuthIdUFFS`, com um campo novo: `token` (que foi usado para criar a entrada no `sessions`).

O cliente mobile guardará o token para usar em qualquer requisição para o web-feedback, assim podemos saber que é o próprio usuário. No futuro podemos melhorar a estrutura do token (usamos um token [paseto](https://github.com/paragonie/paseto), por exemplo), mas para agora está super bom.

No `/logout`, o invocador informa o idUFFS *juntamente* com o `token` que deseja deslogar. Se existir na tabela `sessions` uma entrada para aquele idUFFS com aquele token, removemos a entrada da tabela (deslogamos o dispositivo). Se não existir ou o token for inválido, mandamos o invocador pastar.

**Comment by andrewmsilva** [comment]
Quanto ao Payload, posso submeter o hash da senha usando o mesmo método que usam na API (se usarem algo assim). Se não for o caso, daria pra pensar numa criptografia simétrica para a senha (ou talvez todas as requisições).

Quanto ao retorno da API, vai ser necessário o padrão, como token, id, email, talvez o cpf.

**Comment by JeanCHilger** [comment]
O `token` seria utilizado num cabeçalho (e.g. `authorization`: `$token`)?

**Comment by Dovyski** [comment]
Tu diz em acesso à API depois? Sim, usaremos um [Bearer Token](https://laravel.com/docs/5.8/api-authentication) para autenticar as requisições vindas do app.

**Comment by JeanCHilger** [comment]
> Vamos usar HTTPS para a comunicação, então não precisamos fazer nenhuma criptografia no nosso lado para proteger o password.
> 
> Minha única preocupação é o `/logout`. Da forma que está, qualquer um que saiba o idUFFS de alguém (o que é domínio público) consegue deslogar a pessoa do app.
> 
> Eu sugiro criarmos um modelo chamado `Sessions` com o seguinte:
> 
> ```
> Schema::create('sessions', function (Blueprint $table) {
>     $table->bigIncrements('id');
>     $table->foreignId('user_id');
>     $table->string('token', 60); // usar como valor depois: hash('sha256', Str::random(60));
>     $table->string('device', 250);
>     $table->timestamps();
> 
>    $table->foreign('user_id')->references('id')->on('users');
> });
> ```
> 
> Na chamada ao `/login`, se o usuário é válido, inserimos uma entrada em `sessions`, colocando em `device` o `User Agent` do browser (se vier do mobile, saberemos que dispositivo é). O `/login` retorna as infos retornadas pelo `AuthIdUFFS`, com um campo novo: `token` (que foi usado para criar a entrada no `sessions`).
> 
> O cliente mobile guardará o token para usar em qualquer requisição para o web-feedback, assim podemos saber que é o próprio usuário. No futuro podemos melhorar a estrutura do token (usamos um token [paseto](https://github.com/paragonie/paseto), por exemplo), mas para agora está super bom.
> 
> No `/logout`, o invocador informa o idUFFS _juntamente_ com o `token` que deseja deslogar. Se existir na tabela `sessions` uma entrada para aquele idUFFS com aquele token, removemos a entrada da tabela (deslogamos o dispositivo). Se não existir ou o token for inválido, mandamos o invocador pastar.

Ali na especificação do `/logout`, o `id` seria o id gerado pela aplicação no momento da criação de um usuário (que ocorre no primeiro _login_). Deste modo, seria algo interno, que seria acessado apenas através de `/login`, caso usuário e senha estejam de acordo. Sob estas condições, é necessário a criação de `Session`?

Caso seja necessário, seria algo como é definido na [documentação sobre seções](https://laravel.com/docs/7.x/session)?

**Comment by Dovyski** [comment]
Eu vejo a autenticação pela API e pelo próprio web-feedback como algo diferente. O web-feddback continua autenticando como sempre, porém, via API, o `/api/login` e `/api/logout` são coisas diferentes (elas autenticam e desautentiam usuarios do web-feedback em outros lugares, como o app).

[A documentação de sessão](https://laravel.com/docs/7.x/session)  é sobre como manter o usuário autenticado na própria aplicação (web-feedback). O nome que eu usei é o mesmo, mas não necessariamente a mesma funcionalidade. Podemos chamar a minha `sessions` de `connected_devices`, por exemplo.

**Comment by JeanCHilger** [comment]
@Dovyski, o que aconteceria se um _login_ for efetuado mas nenhum _logout_ ocorrer? Deveria haver um mecanismo de expiração?

**Comment by Dovyski** [comment]
Sim, podemos colocar um cron que apague entradas na tabela `sessions` que forem mais velhas que XX dias, por exemplo.
