### ISSUE TITLE
Ajustar distinção entre as páginas de ideias e serviços

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#125]
Atualmente o sistema está mostrando as páginas de ideias e serviços de forma conjunta, como o conteúdo de "abas". Embora isso tenha funcionado até então, precisamos de uma separação clara entre essas duas páginas. Usuários precisam poder compartilhar links distintos para ambas. Além disso, precisamos de páginas/views separadas porque elas ficarão diferentes entre sí daqui para frente.

O objetivo dessa issue é fazer a implementação (ou ajustes) para que a página [F001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_780) exista e esteja disponível através da url `/feedback`.

**Comment by oraphaBorges** [comment]
As rotas que separam as ideias dos serviços foram criadas e definidos os acessos apenas para quando estiver autenticado, porém a separação do font-end e componentes vai necessitar um pouco mais de trabalho e tempo.

**Comment by oraphaBorges** [comment]
Em tese essa issue está feita, pois as rotas foram feitas, agora falta implementar as paginas de feedbacks #129 e serviços #130 que são outras tarefas.
obs: as rotas são somente acessadas quando o usuário estiver logado.
