### ISSUE TITLE
Criar página inicial para usuários não autenticados (H001-NA)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#127]
A página inicial do sistema deve mostrar um _hero_ (imagem grande abaixo do header) e algumas outras informações de texto. Para o momento atual, podemos implementar essa página como sendo uma cópia da página inicial do site do practice:

![image](https://user-images.githubusercontent.com/512405/96257333-8cfc8a00-0f90-11eb-8127-38926bde14f1.png)

Referência para essa tela: [H001-NA](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_0)

**Comment by oraphaBorges** [comment]
Pagina já criada e 89% pronta

**Comment by oraphaBorges** [comment]
página inicial para acesso não autenticado, feita
