### ISSUE TITLE
Ajustar header da aplicação

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#128]
Atualmente o header da aplicação não está mostrando os links descritos no [documento de referência](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.p). Existem links, mas eles são mostrados de uma forma de "abas" e parecem parte de uma página em específico.

O objetivo dessa issue é ajustar o header para que ele tenha os links corretos (conforme ilustração abaixo) e que mostre as informações do usuário logado (se houver um usuário logado):

![image](https://user-images.githubusercontent.com/512405/96257604-05634b00-0f91-11eb-960a-c93d7482317e.png)

Essa issue não está associada necessariamente a uma tela em específico, porém como referência pode-se usar [H001-NA](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_0) e [H001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_993).

**Comment by oraphaBorges** [comment]
Header criado porém com uma separação de no layout entre menu (com links pra feedback e serviços) e um navbar (com o logo e os dados de login) separados pelo banner

**Comment by oraphaBorges** [comment]
Header finalizado

**Comment by Dovyski** [comment]
Essa tarefa está finalizada. Continuamos os trabalhos em suas respectivas páginas: https://github.com/practice-uffs/web-feedback/issues/129 e https://github.com/practice-uffs/web-feedback/issues/130.
