### ISSUE TITLE
Listagem de serviços que eu solicitei

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#131]
Depende de: #130 

Implementar a listagem de serviços que um usuário solicitou. Esse conteúdo é mostrado na seção "Serviços que eu solicitei" na tela de serviços [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657):

![image](https://user-images.githubusercontent.com/512405/96258395-59226400-0f92-11eb-8c86-094be13133a8.png)

A listagem dos serviços deve mostrar o título dele, uma pequena descrição (talvez os 200 primeiros chars que o usuário digitou na descrição), a categoria do serviços, a data de criação, o id do serviço (id no banco), e o um link para acompanhar o serviço.

Ao clicar no link para acompanhar, o usuário é levado para a página [I002-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_1405)

Tela de referência: [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657)

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-12 09-15-44](https://user-images.githubusercontent.com/22224088/98939333-091eba80-24c8-11eb-9189-3ac366f2fd04.png)
