### ISSUE TITLE
Listagem de solicitação de serviços - Vídeo

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#133]
Depende de: #130 

Implementar a listagem de serviços disponíveis para solicitação na seção _Vídeo_, conforme listado na tela [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657).

Cada um dos serviços a serem listados devem ter um ícone, um título, uma descrição, um botão para solicitação e uma informação sobre o prazo para que o serviço seja concluído. Todas as informações referentes aos serviços de vídeo existentes estão listadas [aqui](https://practice.uffs.cc/servico/midia/).

Tela de referência: [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657)

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-12 20-47-25](https://user-images.githubusercontent.com/22224088/99010323-8a0d9e80-2528-11eb-971d-4700d89e1850.png)
