### ISSUE TITLE
Listagem de solicitação de serviços - Estúdio

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#134]
Depende de: #130 

Implementar a listagem do serviço disponíveis para solicitação na seção _Estúdio_, conforme listado na tela [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657) (a tela não mostra essa seção, mas ela é igual às seções de áudio e vídeo).

Cada um dos serviços a serem listados devem ter um ícone, um título, uma descrição, um botão para solicitação e uma informação sobre o prazo para que o serviço seja concluído. Todas as informações referentes aos serviços de estúdio existentes estão listadas [aqui](https://practice.uffs.cc/servico/estudio/).

Tela de referência: [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657)

**Comment by oraphaBorges** [comment]
![Uploading Captura de tela de 2020-11-13 10-08-58.png…]()

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-13 10-08-58](https://user-images.githubusercontent.com/22224088/99075629-8e71a000-2598-11eb-8a37-ce2a2e522b22.png)
