### ISSUE TITLE
Listagem de solicitação de serviços - Texto e imagem

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#135]
Depende de: #130 

Implementar a listagem de serviços disponíveis para solicitação na seção _Texto e imagem_, conforme listado na tela [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657) (a tela não lista essa seção em específico, mas ela segue a mesma estrutura das outras seções).

Cada um dos serviços a serem listados devem ter um ícone, um título, uma descrição, um botão para solicitação e uma informação sobre o prazo para que o serviço seja concluído. Todas as informações referentes aos serviços de texto e imagem existentes estão listadas [aqui](https://practice.uffs.cc/servico/conteudo/).

Tela de referência: [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657)

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-13 10-08-19](https://user-images.githubusercontent.com/22224088/99075485-54a09980-2598-11eb-8d2e-e874381afdad.png)

![Captura de tela de 2020-11-13 10-08-31](https://user-images.githubusercontent.com/22224088/99075501-59fde400-2598-11eb-8713-ea3d245f52ab.png)
