### ISSUE TITLE
Listagem de solicitação de serviços - Evento virtual

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#136]
Depende de: #130 

Implementar a listagem do serviço disponível para solicitação na seção _Evento virtual_, conforme listado na tela [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657) (a página não mostra essa seção em específico, mas a estrutura é a mesma das outras seções).

Cada um dos serviços a serem listados devem ter um ícone, um título, uma descrição, um botão para solicitação e uma informação sobre o prazo para que o serviço seja concluído. Todas as informações referentes aos serviços de evento virtual existente está listada [aqui](https://practice.uffs.cc/servico/evento-virtual/).

Tela de referência: [S001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.ga3a9deaf14_0_657)

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-13 10-08-50](https://user-images.githubusercontent.com/22224088/99075566-74d05880-2598-11eb-89d6-4671834d6f31.png)
