### ISSUE TITLE
Criar estrutura inicial do módulo lousa (L001-A)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#137]
Criar a rota `/lousa`, a view e a estrutura de layout inicial (elementos de interação, porém que não respondem a clicks e afins) da página [L001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9864992a6c_0_5).

Na seção que lista as lousas, nada precisa ser mostrado, apenas a seção precisa existir. A listagem de lousas existentes será implementada em uma issue em separado.

Tela de referência: [L001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9864992a6c_0_5).

![image](https://user-images.githubusercontent.com/512405/96259735-68a2ac80-0f94-11eb-9fd9-494352dc5fd0.png)

**Comment by CleissonVieira** [comment]
Estrutura inicial concluída:

![image](https://user-images.githubusercontent.com/29258164/99023325-1a58dd00-2543-11eb-829b-ac2b857aefad.png)
