### ISSUE TITLE
Implementar estrutura inicial de uma página de lousa ativa (L002-A)

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#138]
Criar a rota `/lousa/{código}`, a view e a estrutura de layout inicial (elementos de interação, porém que não respondem a clicks e afins) da página [L002-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9974c023d9_0_43).

Na seção que lista as lousas, nada precisa ser mostrado, apenas a seção precisa existir. A listagem de lousas existentes será implementada em uma issue em separado.

Tela de referência: [L002-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9974c023d9_0_43).

![image](https://user-images.githubusercontent.com/512405/96259993-c20adb80-0f94-11eb-9c19-ad09d7d198b1.png)

**Comment by CleissonVieira** [comment]
Sofri para fazer isso gente, acreditem ou não hehe
Mas primeira versão está assim, estava cheia de ideias, coloquei várias outras funções mas fui tirando porque bugava outras funções. Então pra dar sequência adiei

![image](https://user-images.githubusercontent.com/29258164/101313868-06e51d00-3836-11eb-8890-4bbe039cabb3.png)

**Comment by Dovyski** [comment]
Ficou lindo! ❤️
