### ISSUE TITLE
Criar estrutura do banco de dados para Whiteboard

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#139]
Criar o modelo, tabela e migrations relacionadas ao item `whiteboards` no banco de dados. Informações sobre as  relações desse item estão no [modelo relacional](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_1930).

**Comment by CleissonVieira** [comment]
Estrutura no banco finalizada

![image](https://user-images.githubusercontent.com/29258164/100125404-84368800-2e5b-11eb-9d66-462551486ba5.png)
