### ISSUE TITLE
Criar página /items/{id}/comment

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#14]
Depende de #13

A página `/item/{id}/comment` permite que um usuário comente um item. Na modelagem do banco de dados, o modelo `Item` representa tanto ideias/feedbac/críticas/etc quando comentários (todos são modelados para a mesma tabela). A diferença está no campo `parent_id`. Se ele for nulo, significa que o item é uma ideia/sugestão/etc. Se o `parent_id` for um inteiro (que é o id do item a qual ele se refere), significa que esse item é um comentário do item com `id == parent_id`.

**Comment by JeanCHilger** [comment]
ao invés de uma página, poderia ser um campo a baixo dos comentários existentes (parecido com o github) ou então um botão que abre um modal?

**Comment by Dovyski** [comment]
Sim, esse seria o ideal. Eu não coloquei dessa forma inicialmente porque achei que seria mais complicado. Se tu julgar que vale o esforço fazer com um campo abaixo dos comentários existentes (exatamente como é no github), por favor, faça desssa forma ❤️ .

**Comment by JeanCHilger** [comment]
Um usuário poderá adicionar quantos comentários desejar ou terá um limite?
