### ISSUE TITLE
Criar estrutura do banco de dados para Sticker

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#140]
Criar o modelo, tabela e migrations relacionadas ao item `stickers` no banco de dados. Informações sobre as  relações desse item estão no [modelo relacional](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_1930).

**Comment by CleissonVieira** [comment]
Estrutura finalizada. Perdão pela atrapalhada, inverti o número da issue, fiz a 141 na 140 e vice-versa.

![image](https://user-images.githubusercontent.com/29258164/100149966-b22cc400-2e7d-11eb-9885-bde93dbb00ef.png)
