### ISSUE TITLE
Criar estrutura do banco de dados para Interaction

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#141]
Criar o modelo, tabela e migrations relacionadas ao item `interactions` no banco de dados. Informações sobre as  relações desse item estão no [modelo relacional](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_1930).

**Comment by CleissonVieira** [comment]
Estrutura finalizada

![Uploading image.png…]()
