### ISSUE TITLE
Criação de lousa

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#142]
Depende de: #139,  #138 

Se o usuário estiver navegando pela página [L001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9864992a6c_0_5), o botão "Criar nova lousa" pode ser clicado. Se isso acontecer, o sistema deve criar uma nova lousa da seguinte forma:

* Inserir uma nova entrada na tabela `whiteboards`;
* Redirecionar o usuário para a rota `/lousa/{código}`, onde `{código}` é  uma string (campo `hash` do modelo) da lousa recém criada (o layout dessa página está referenciada como [L002-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9974c023d9_0_43)).

Para criação da string que será colocada no campo `hash` do modelo recém criado, fazer o `md5` do id do modelo e utilizar os 6 primeiros chars do resultado do hash.

**Comment by CleissonVieira** [comment]
Com as novas visões dos projetos do dev não vejo mais sentido nessa issue, mas sim em um novo pensamento e reestruturação para o classroom.
