### ISSUE TITLE
Implementar seção "Minhas lousas"

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#143]
Depende de: #139 #138 

Implementar a seção "Minhas lousas", que lista as lousas que um usuário possui, conforme descrito na tela [L001-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9864992a6c_0_5).

A listagem da lousa deve conter título da lousa, data de criação, o hash (código), um botão para apagar a lousa (com um modal para confirmação dessa ação) e um botão para acessar a lousa (que leva para a tela [L-002-A](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g9974c023d9_0_43)).

**Comment by CleissonVieira** [comment]
Com as novas visões dos projetos do dev não vejo mais sentido nessa issue, mas sim em um novo pensamento e reestruturação para o classroom.
