### ISSUE TITLE
Implementar reações em um item

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#15]
Ao visualizar qualquer item (seja ele uma ideia/sugestão/etc) ou um comentário, o usuário pode reagir a ele (da mesma forma que usuários do Github podem reagir a comentários em issues). A reação é basicamente o usuário colocar o mouse sobre uma área do conteúdo, uma lista de emojis é mostrada, o usuário clica em uma delas e a reação fica atrelada ao item. Se o usuário clicar sobre o emoji de reação depois de ele ter sido escolhido, a reação é removida.

**Comment by JeanCHilger** [comment]
Essa issue foi parcialmente resolvida em #46. Devido à complexidade encontrada, esta issue será fechada, e novas serão criadas.
