### ISSUE TITLE
Atualização da logo

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/web-feedback#150]
Conforme foi produzido na issue [247](https://github.com/practice-uffs/programa/issues/247), requisito que a logo do web-feedback seja atualizada com a nova logo produzida pelo @practice-uffs/con-design. Basta acessar a issue, ir no drive e acessar a imagem.

**Comment by estelavilasboas** [comment]
[Pasta da issue programa#247](https://drive.google.com/drive/folders/1SLuYscoyrseQy-mJzNKvjI0yAgFv7R4H)

**Comment by oraphaBorges** [comment]
Perfeita!!

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-12 08-48-14](https://user-images.githubusercontent.com/22224088/98936633-fa360900-24c3-11eb-8d20-02b2098563f4.png)

**Comment by andrewmsilva** [comment]
Tá show de bola! Só acho que a logo poderia ficar um pouco mais à esquerda, mais ou menos no mesmo nível do título centralizado logo abaixo. Aliás, já que a lgoo já tem o nome do site, saria pra tirar o título centralizado. Mas são só sugestões, já tá show.
