### ISSUE TITLE
Refinar usuários locais e criar flag de administrador

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#155]
Verificar se usuários locais estão sendo criados no web-feedback. Usuários locais são usuários criados via `User` no Laravel com base numa autenticação bem sucedida com o idUFFS.

Além disso, adicionar um novo campo `administrator` (bool) no modelo `User` para indicar se um usuário é um administrador. Fazer a checagem na página de postagem de comentários em um serviço que somente o autor do serviço pode comentar ou um usuário administrador.

**Comment by oraphaBorges** [comment]
Analisando os objeto Users já há uma flag q define se o usuário é admin ou não (a flag: type). Não é a mais indicada implementação de permissões de usuários, mas quebra um galho para os níveis de permissões que pretende-se implementar no momento (usuários e admin).
