### ISSUE TITLE
Página de administrador para listagem de serviços

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#156]
Um usuário administrador autenticado deve ter acesso a uma página que lista todos os serviços cadastrados no sistema. A listagem pode ser semelhante à listagem já existente na página de serviços atuais. Adicionalmente, um serviço listado deve mostrar quem é o autor da solicitação e quem foi o último usuário que comentou no serviço (inclusive com uma informação do tipo `"Atualizada há 3 dias"`.)

Ao clicar em um desses serviços, o usuário é levado para a página já existente de visualização de serviços, onde as interações (como comentários) devem ser feitas.

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-24 11-04-50](https://user-images.githubusercontent.com/22224088/100104689-43337900-2e45-11eb-9372-fccd51e7e170.png)

**Comment by oraphaBorges** [comment]
os usuários administradores são adicionados manualmente no fonte (por enquanto), sendo assim, quem for testar o modulo admin  favor me mandar o idUFFS para ser incluso.
