### ISSUE TITLE
Melhor documentar quais endpoints existem no web-feedback

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#158]
Atualizar o `README` do projeto com uma listagem de todos os endpoints disponíveis, seus verbos de acesso e parâmetros.  Talvez utilizar uma tabela como é feito com a [api-cc](https://github.com/ccuffs/api-cc#endpoints) seja simples e interessante.

**Comment by oraphaBorges** [comment]
A documentação pode ser acompanhada através do gerador de documentação do Postman [neste link](https://documenter.getpostman.com/view/11057697/TVetbmFy)

**Comment by oraphaBorges** [comment]
> A documentação pode ser acompanhada através do gerador de documentação do Postman [neste link](https://documenter.getpostman.com/view/11057697/TVetbmFy)

As vantagens de usar esse serviço é que toda a documentação já está estilizada automaticamente, fica sincronizada com a aplicação do Postman, sendo assim condizente com os teste e também sendo possível definir as variáveis de ambientes, colaboradores e a visualização com exemplos em diversas linguagens de programação.

**Comment by andrewmsilva** [comment]
Achei bem maneiro. Daria pra adicionar esse link ali no Readme também :D

**Comment by andrewmsilva** [comment]
Mesmo com as alterações, ainda estou recebendo 404 ao acessar o [endpoint](https://qa.mural.practice.uffs.cc/api/specifications)
