### ISSUE TITLE
Transformar json de serviços em specifications e criar endpoint

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#159]
Há um json que lista os tipos de serviços, suas descrições e prazos. Migrar esse json para entradas no no banco de dados na tabela/modelo `specifications`. Além disso, criar um enpoint `/specifications` que lista as especificações (serviços) existentes, com as mesmas informações do arquivo json.

**Comment by andrewmsilva** [comment]
Trabalhando na issue [#69](https://github.com/practice-uffs/app-practice/issues/69) do app, tentei utilizar o endpoint criado, mas recebi um erro 404. Acho conveniente dar uma olhadinha.

**Comment by oraphaBorges** [comment]
> Trabalhando na issue [#69](https://github.com/practice-uffs/app-practice/issues/69) do app, tentei utilizar o endpoint criado, mas recebi um erro 404. Acho conveniente dar uma olhadinha.

esse erro é por conta de um problema do deploy e foi reportado na issue #162, assim que esse problema for resolvido o endpoint estará disponível

**Comment by andrewmsilva** [comment]
O problema foi resolvido, mas o endpoint ainda está resultando em 404.

**Comment by oraphaBorges** [comment]
> O problema foi resolvido, mas o endpoint ainda está resultando em 404. Talvez seja apenas alguns detalhes, mas é necessário verificar.

Este problema está persiste porque nem migrates e o seed do specification foram executados no deploy.
