### ISSUE TITLE
Adaptar modal de solicitação para trabalhar com novas entradas de specifications

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#160]
Ao solicitar um novo serviço, no modal de solicitação, um usuário deve ver as informações de `specifications` do serviço em questão. Isso serve para que cada serviço possa ser solicitado com um conjunto de informações diferentes entre si.

**Comment by oraphaBorges** [comment]
![Captura de tela de 2020-11-27 11-01-00](https://user-images.githubusercontent.com/22224088/100456926-df58bc80-309f-11eb-8d8e-7608cdb962a0.png)
