### ISSUE TITLE
[BUG] Não execução do Seed de Specifications no Deploy

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/web-feedback#167]
O merge com as correção do deploy foi feito e ao menos no ambiente de desenvolvimento está ok, entretanto no ambiente de homologação e testes não ele não esta executando o seed de specifications para fazer a pré-população do banco de dados.

![Captura de tela de 2020-11-25 08-36-33](https://user-images.githubusercontent.com/22224088/100223204-efcf3280-2ef9-11eb-8677-6e8be1bcf319.png)

eu conferi os arquivos e o seed do especifications está inserido na rotina de execução dos seeds.

![Captura de tela de 2020-11-25 08-41-46](https://user-images.githubusercontent.com/22224088/100223326-1beab380-2efa-11eb-8579-9081055f22b3.png)

**Comment by oraphaBorges** [comment]
Investigando mais um pouco encontrei o problema com o Doctrine\DBAL

![Captura de tela de 2020-11-25 09-14-29](https://user-images.githubusercontent.com/22224088/100226644-c8c72f80-2efe-11eb-8320-c7fd61dea91c.png)

mesmo essa lib estando presente no composer, aparentemente o composer não instalou essa dependencia

![Captura de tela de 2020-11-25 09-15-59](https://user-images.githubusercontent.com/22224088/100226780-f8763780-2efe-11eb-8733-af99e62a848d.png)

**Comment by oraphaBorges** [comment]
Suspeita-se que há um conflito no aquivo `public/js/app.js` que é o arquivo onde o vue concentra a renderização de todos os componentes e que em tese é gerado no processo de deploy com o  `npm run production`. Como esse arquivo ele vem sendo enviado nos commits (pois cada mudança nos componentes do vue ele tb é alterado), pode haver um conflitos que impende o deploy de ser finalizado com sucesso.

Fiz um teste colocando esse aquivo no `.gitignore`  e o removendo para que o deploy faça a criação dele, porém o processo de deploy está dando um erro dizendo que não consegue se conectar sem a chave privada do ssh ou senha.

![Captura de tela de 2020-11-25 10-08-22](https://user-images.githubusercontent.com/22224088/100231786-417dba00-2f06-11eb-9997-e0d7893c99b7.png)

**Comment by oraphaBorges** [comment]
No ultimo pull request foi corrigido e criado o `specification` no banco, porém os `seeders` não foram executados, assim o retorno dos `endpoints` de categorias, localização e especificação estão vazios.

**Comment by Dovyski** [comment]
Minha cagada. Acabei de rodar os seeds em QA e produção. Pode conferir se tudo está ok por favor, @oraphaBorges ?

**Comment by oraphaBorges** [comment]
@Dovyski conferido e agora está tudo correto!
