### ISSUE TITLE
Implementar /service/create

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#17]
A página `/service/create` tem a mesma funcionalidade que a página de criar um item. A diferença é que um serviço está vinculado obrigatoriamente a uma categoria (category) e, internamente, ele é usado pela equipe para saber que um membro da comunidade acadêmica precisa de algo.

**Comment by arufonsekun** [comment]
Tenho algumas dúvidas sobre essa _issue_:
- Internamente um **serviço** é um **item**, o que diferencia tudo é o campo `type`, certo?
- Os serviços serão visualizados somente pelos integrantes do practice?

**Comment by Dovyski** [comment]
>
>    - Internamente um *serviço* é um *item*, o que diferencia tudo é o
>    campo type, certo?
>
> Sim, exatamente isso. No futuro próximo, também teremos que criar
comentários (que são itens cujo parent_id é outro item).

Eu fiz a modelagem usando apenas uma tabela porque, no final, tudo será a
mesma coisa (o que permite reuso de tudo).


>    - Os serviços serão visualizados somente pelos integrantes do practice?
>
> Sim, e pelo próprio autor do pedido. Acho que podemos filtrar essa
visualização de itens apenas pelo campo hidden. Serviços são hidden por
padrão e tem um type específico.
