### ISSUE TITLE
Alterar endpoints para validar token dos usuários

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/web-feedback#170]
Visto que segurança é um fator importante, é necessário que os endpoints que exijam os IDs dos usuários sejam alterados para que recebam um token que deve ser decodificado para identificar o usuário. Feito isso, deve-se realizar a tarefa requisitada ou nega-la, se for o caso (erro 401). 

Pode ser que também seja necessário adicionar essa validação em endpoints que, atualmente, não exigem IDs dos usuários, como a que carrega os comentários de um serviço específico. Se julgarem que não há a necessidade disso, sem problemas.

**Comment by oraphaBorges** [comment]
Criada a validação dos endpoints com token, para isso foi utilizado a lib [JWT ](https://jwt-auth.readthedocs.io/) seguindo o tutorial do [Robson V. Leite](https://www.youtube.com/watch?v=Ri-DLFeepbM&t=1571s).

Os novos endpoint e os endpoints que necessitarão do token para serem acessados, podem ser conferidos na [documentação da API](https://documenter.getpostman.com/view/11057697/TVetbmFy)
