### ISSUE TITLE
Ajustar status dos Serviços

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/web-feedback#171]
Coforme discussão feita anteriormente, constatou-se que seria conveniente ajustar os status dos Serviços. A primeira sugestão possível seria utilizar os mesmos status que utilizamos aqui no GitHub (_Fazer_, _Em progresso_ e _Pronto_), mas também seria possível definir status um pouco mais claros para o usuário, como _Aguardando_, _Em execução_ e _Concluído_. A escolha final fica a critério de quem fizer a tarefa.

Outra opção seria criar manter os status como números (_1_, _2_ e _3_) e definirmos no código a mensagem a ser mostrada. Creio que ficaria mais simples.

Se houver algum problema em fazer isso, como impedimentos do nosso banco de dados, favor informar.

**Comment by oraphaBorges** [comment]
Como no banco já havia o campo de `status` no `ítem` e ele é numérico, optei por deixar assim e definir o status como:
```
STATUS_WAITING       = 1; // Aguardando
STATUS_PROGRESSING   = 2; // Em Progresso
STATUS_CONCLUDED     = 3; // Concluído
```
