### ISSUE TITLE
Postar comentários em issue do github quando algum comentário é criado no web-feedback

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#181]
Essa issue está relacionada com #180 

Quando houver uma interação com um serviço no web-feedback (como comentário de um cliente ou de um admin), essa interação deve ser refletida no github também para não termos um "telefone sem fio". O objetivo dessa issue é fazer essa integração.

Os serviços no webfeedback tem um campo relacionado com um link de uma issue. Logo, quando um comentário for criado em um serviço, pode-se verificar se o campo da URL da issue tem alguma coisa. Se tiver, quer dizer que esse serviço está relacionado com uma issue. Com a URL da issue, pode-se utilizar a API do github para postar um comentário nessa issue em específico.

**Comment by oraphaBorges** [comment]
realizada as tarefe de:
- [x] comentar na issue do github e ir para o webfeedback
- [x] comentar na solicitação no webfeedback e ir para os comentarios das issues do github

**Comment by oraphaBorges** [comment]
@Dovyski Necessário criar 2 variáveis de ambiente no `.env`, para que o webfeedback possa se conectar ao Github e enviar os comentários feitos.

para o ambiente de homologação/teste:
```
GIT_REPO=https://api.github.com/repos/practice-uffs/playground/ 
```
para o ambiente de produção:
```
GIT_REPO=https://api.github.com/repos/practice-uffs/web-feedback/ 
```

e gerar o token de acesso pessoal da conta do practice neste [link](https://github.com/settings/tokens), e salvar nos `.env` (de homologação/teste e produção) como:
```
GIT_TOKEN={{token gerado}}
```
