### ISSUE TITLE
Chave JWT no .env

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/web-feedback#189]
A autorização JWT está retornando `500 internal server error` e aparentemente esse erro está o correndo porque no deploy não foi gerada a chave secreta do JWT que ficará salva no `.env`.

Favor verificar se a chave foi gerada, caso não tenha sido, executar o comando `php artisan jwt:secret`

**Comment by Dovyski** [comment]
Deve estar resolvido agora. Pode conferir por favor, @oraphaBorges ?

**Comment by oraphaBorges** [comment]
Conferido e aprovado, agora está funcionado perfeitamente.

**Comment by Dovyski** [comment]
❤️🥳
