### ISSUE TITLE
Criar endpoint para criação de comentários

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/web-feedback#190]
Visto que será possível comentar uma solicitação de serviço pelo app, é necessário que seja disponibilizado um endpoint para realizar um `POST` à api.

**Comment by oraphaBorges** [comment]
Endpoint já estava criado, só faltava ser documentado.
Agora o endpoint encontra-se documentado e disponível na [documentação](https://documenter.getpostman.com/view/11057697/TVetbmFy)
