### ISSUE TITLE
Ajustar login principal

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/web-feedback#191]
A maioria das funcionalidades do site estão sendo realizadas através da api, o que é algo bom. No entanto, o login ainda é feito diretamente pelo Laravel e, como foram criados mecanismos de segurança utilizando tokens, é necessário ajustar o login do site para consumir a api também. Dessa forma, quaisquer problemas relacionados aos tokens são evitados.

**Comment by oraphaBorges** [comment]
Resolvi este problema passando o token para o session ao logar e daí passar para o Vue.js o token pelo Laravel
