### ISSUE TITLE
Filtrar comentários Github->sistema com base em uma string

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#206]
Quando algum comentário for postado no github, ele deve ser postado no web-feedback também (se houver uma solicitação linkada a essa issua lá). Essa postagem deve ser, porém, baseada em uma string: se o comentário na issue do github tiver `@cliente` em qualquer lugar, o comentário deve ser postado, caso contrário, não (assume que é comentário de trabalho no github).

**Comment by oraphaBorges** [comment]
Comentários que são feitos no github só irão para o webfeedback caso haja a tag `#cliente`

**Comment by andrewmsilva** [comment]
O que acham que remover a tag `#cliente` do que é salvo no Mural? Tipo, continua funcionando do mesmo jeito, mas, na hora de salvar o comentário no Mural, remove o `#cliente` pra não ficar aparecendo isso no comentário.

**Comment by oraphaBorges** [comment]
> O que acham que remover a tag `#cliente` do que é salvo no Mural? Tipo, continua funcionando do mesmo jeito, mas, na hora de salvar o comentário no Mural, remove o `#cliente` pra não ficar aparecendo isso no comentário.

resolvido! (o vue estava removendo apenas um "#cliente" e agr está removendo todos)
