### ISSUE TITLE
Roteiro de Teste

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/web-feedback#210]
Fazer o roteiro e documentação de testes do webfeeback para poder ir ao ar 100%.
- [x] Formulário de teste para feedback
- [x] Roteiro de teste para usuário
- [x] Roteiro de teste para administradores 

A bateria de teste será aberta para diferentes grupos com membros do PRACTICE e comunidade acadêmica.

**Comment by oraphaBorges** [comment]
Realizado o roteiro e formulário de testes que está disponível na pasta da Isusse no [drive](https://drive.google.com/drive/folders/10lNjiFTXtvkA3BFUp32v1vt82CYcBL0E?usp=sharing) e através deste [link](https://forms.gle/dUbaxJw1o2UyW4dN6). 

Se puderem (@Dovyski, @andrewmsilva e @CleissonVieira) gostaria de um feedback sobre o roteiro e perguntas do formulário.

Com tudo ok, faremos o convite para os usuário fazerem o teste do sistema em 2 fases:
**fase 1**: selecionaremos apenas membros do Practice.
a partir dos retornos, faremos as correções, se necessárias, e partiremos para a próxima fase.
**fase 2**: os testes serão realizado por um grupo maior que da fase anterior, que incluam alguns membros da comunidade acadêmica (professores, alunos e TAEs).
a partir dos retornos, faremos as correções, se necessárias, e o Web-feedback já estará pronto para disponibilização.

**Comment by andrewmsilva** [comment]
Fiz umas pequenas correções no formulário e queria trazer uma discussão aqui. Nós nos acostumamos a usar o termo "web-feedback" por conta do nome do projeto, mas o nome que ele muito provavelmente vai ser conhecido pelas pessoas é Mural PRACTICE. O que acham de adotarmos esse nome daqui pra frente sempre que mencinarmos este projeto em algo (como no formulário de testes)? Porque esse é nome da aplicação e acho que seria apropriado usá-lo, pois evitaria possíveis confusões e tornaria tudo mais claro pra quem está testando e usando.

**Comment by oraphaBorges** [comment]
É um bom levantamento, mas pessoalmente prefiro o nome web-feedback para o projeto que se refere a gerencia das solicitações do PRACTICE e o mural ser as aplicações de inovação em sala de aula, com a lousa digital, por exemplo.

**Comment by andrewmsilva** [comment]
O deploy não foi feito no dev. Aparentemente houve algum erro ao instalar as dependências.
