### ISSUE TITLE
Commits em inglês?

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#22]
Vamos fazer os commits em ingles como fizemos com o app-covid, @JeanCHilger @arufonsekun ?

**Comment by arufonsekun** [comment]
Acho que sim

**Comment by Dovyski** [comment]
Ok então. Vou usar commits semanticos só nos commits de merge de PR.

**Comment by JeanCHilger** [comment]
Como foi optado por commit em inglês, esta issue será fechada
