### ISSUE TITLE
Aprimorar páginas internas para integrar com novo layout

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#223]
Essa issue depende de #220 (PR #222)

Depois que o PR #222 for mergeado, as páginas internas do web-feedback precisam ser ajustadas para que acompanhem o novo layout da index. Eu não fiz isso de imediato porque todo o sistema interno está em vue.

Os componentes vue precisam ser atualizados (talvez até alguns removidos, como o header/navbar) para seguir o novo layout.

**Comment by oraphaBorges** [comment]
Feito as adaptações do novo layout para o Vue.js e gostaria de alguns apontamentos do @Dovyski e da @estelavilasboas para melhorias do UI

**Comment by oraphaBorges** [comment]
Nova tela de login 
![Captura de tela de 2021-02-19 15-52-38](https://user-images.githubusercontent.com/22224088/108548447-9abd7580-72ca-11eb-8749-4360db8fbe4d.png)

**Comment by oraphaBorges** [comment]
Lova home page

![Captura de tela de 2021-02-19 15-54-02](https://user-images.githubusercontent.com/22224088/108548756-0bfd2880-72cb-11eb-8ea2-cbbd43f93b7b.png)
![Uploading Captura de tela de 2021-02-19 15-54-02.png…]()
![Captura de tela de 2021-02-19 15-54-37](https://user-images.githubusercontent.com/22224088/108548761-0c95bf00-72cb-11eb-9637-3e2445037246.png)
![Captura de tela de 2021-02-19 15-54-48](https://user-images.githubusercontent.com/22224088/108548762-0d2e5580-72cb-11eb-9497-fd1083d5ac3b.png)
![Captura de tela de 2021-02-19 15-55-07](https://user-images.githubusercontent.com/22224088/108548763-0dc6ec00-72cb-11eb-8f36-f34f9554cda1.png)
![Captura de tela de 2021-02-19 15-55-16](https://user-images.githubusercontent.com/22224088/108548764-0dc6ec00-72cb-11eb-9596-e2bb2c4db93f.png)
![Captura de tela de 2021-02-19 15-55-54](https://user-images.githubusercontent.com/22224088/108548767-0e5f8280-72cb-11eb-9464-dc7e599e204a.png)
![Captura de tela de 2021-02-19 15-56-09](https://user-images.githubusercontent.com/22224088/108548768-0ef81900-72cb-11eb-9572-991f60c863d6.png)

**Comment by oraphaBorges** [comment]
Nova página para acompanhar o desenvolvimento das  solicitações separados pelos status

![Captura de tela de 2021-02-19 15-57-12](https://user-images.githubusercontent.com/22224088/108548977-541c4b00-72cb-11eb-8f58-c630ab9de5f8.png)
![Captura de tela de 2021-02-19 15-57-25](https://user-images.githubusercontent.com/22224088/108548978-54b4e180-72cb-11eb-9b96-5087d7daaa46.png)
![Captura de tela de 2021-02-19 15-57-35](https://user-images.githubusercontent.com/22224088/108548982-554d7800-72cb-11eb-967c-28b081b5b7df.png)

**Comment by oraphaBorges** [comment]
Nova página separada para fazer a solicitação de serviços

![Captura de tela de 2021-02-19 15-59-32](https://user-images.githubusercontent.com/22224088/108549118-82018f80-72cb-11eb-854f-9f94f6a3fb02.png)

**Comment by oraphaBorges** [comment]
Alteração do layout da para a listagem dos serviços separados por status para os admins do practice

![Captura de tela de 2021-02-19 16-00-54](https://user-images.githubusercontent.com/22224088/108549272-aeb5a700-72cb-11eb-985c-68f2140265b4.png)
