### ISSUE TITLE
[FRONT] Adicionar dashboard à base

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#25]
Adicionar a dashboard [homer](https://github.com/bastienwirtz/homer) à base.

Apenas os arquivos estáticos são necessários, a princípio.

**Comment by JeanCHilger** [comment]
@Dovyski esse layout será utilizado na página inteira ou só na view dos itens?

**Comment by Dovyski** [comment]
Nesse primeiro momento, acho que pode ser só nessa view para reduzir o escopo de trabalho. No futuro colocamos ela para o resto do site (ou adaptamos para um meio termo).
