### ISSUE TITLE
Desativar temporariamente a integração com o Github

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/web-feedback#260]
Desativar temporariamente a integração com o Github para a apresentação do projeto.

**Comment by andrewmsilva** [comment]
Houve falha no deploy ao instalar as dependências. É necessário revisar.

**Comment by andrewmsilva** [comment]
Conforme @oraphaBorges me disse, isso está funcionando mesmo tendo dado esse erro nos checks. Vou fechar a issue, mas seria bom se o @Dovyski desse uma verificada nisso.
