### ISSUE TITLE
Adicionar cadastro para a newsletter

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#270]
Na página inicial do sistema, temos uma parte para que usuários se inscrevam em nossa newsletter. Isso precisa ser implementado. [Esse pacote](https://mydnic.be/post/super-simple-laravel-newsletter-subscribers-system) permite que isso seja feito de uma forma fácil e rápida.

**Comment by oraphaBorges** [comment]
@Dovyski Incluído a lib de coleta de subscribers para a newsletter. Executar os seguintes comandos para poder incluir o  provider e gerar o migrate para funcionamento do banco e entrar em funcionamento:
```
php artisan vendor:publish --provider="Mydnic\Subscribers\SubscribersServiceProvider" --tag="subscribers-migrations"
php artisan migrate
```

**Comment by oraphaBorges** [comment]
comandos executados e funcionando!
