### ISSUE TITLE
Revisão dos TIPOS e PRAZOS dos serviços de vídeos

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/web-feedback#274]
No MURAL do PRACTICE existe a possibilidade de solicitar um serviço de vídeo e mídia (lives). Sugiro que a gente revise os tipos de vídeos que deverão ser colocados lá, bem como os prazos que deverão ser colocados em cada tipo de vídeo. 

*Lembrando que tínhamos pensado em deixar um prazo variável, mas não sei como isso vai funcionar. 

Para isso a gente precisa da ajuda de todos do @practice-uffs/con-midia. 

Por favor, deem suas opiniões.

**Comment by oraphaBorges** [comment]
Fazendo essa revisão e passando direitinho todos os serviços por categorias e prazos, fazer essa alteração não é complicada @robisonjose . Os serviços no Mural estão seguindo a forma como estão no site do practice, a menos que tenham sido alterados por lá e acabamos não refletindo essas alterações por aqui.

**Comment by MaNegrao** [comment]
@practice-uffs/con-midia em conjunto com a issue do rep programa [#428](https://github.com/practice-uffs/programa/issues/428) é necessario a definição desses tipos de vídeos e prazos, já que o mural está no ar e com solicitações. O robson já fez um esboço na issue do rep programa, basta agora bater o martelo e finalizar.

**Comment by robisonjose** [comment]
Robison*

**Comment by CleissonVieira** [comment]
@robisonjose Não seria interessante levar como ponto para uma reunião de líderes, finalizar a issue e criar uma nova após ter definido o que será alterado?

**Comment by robisonjose** [comment]
Vamos fazer isso internamente com o mídia. Assim que tivermos tudo resolvido, abro outra issue.
