### ISSUE TITLE
Revisão textual do mural

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/web-feedback#276]
é necessário fazer a revisão textual em todas as páginas do Mural.

@thaliafriedrich por favor, trate desta tarefa.

**Comment by thaliafriedrich** [comment]
Fiz a revisão textual do Mural. Deixo abaixo todas as correções e sugestões.
Obs.: Algumas vezes fiz alteração de palavras, mas na maioria das vezes foram correções de pontuação ou acentuação. Vou escrever aqui os textos corrigidos, com destaque em negrito para o que foi alterado.

 **PÁGINA INICIAL**

- Texto da descrição de Boas-vindas": adicionar vírgula entre "programa" e "onde". ("Essa é a plataforma oficial do programa, onde a comunidade...).
- Pilares que nos norteiam. Sugiro alterar para "Pilares que norteiam nosso trabalho". E no bloco Comunidade, fiz umas correções no texto: "Não estamos sós, focamos na habilidade pedagógica e **tecnológica, tanto** de servidores quanto **de** estudantes."

- ALGUMAS DE NOSSAS ESTATÍSTICAS
            Já produzimos cerca de
(Manter o mesmo padrão dos outros títulos e subtítulos da página, com título em letra maiúscula e subtítulo em letra minúscula, e remover a palavra “onde”).
Onde diz "Entidades + Entidades Visuais" corrigir para "Identidades Visuais".  Conferir os números no geral, pois vi que estão diferentes dos que foram informados na notícia que escrevemos a partir da pesquisa de satisfação.

- SERVIÇOS
1. Descrição corrigida para o bloco de Áudio: Faixas de áudio com objetivo de anunciar e/ou divulgar algo, **fazer** uma chamada ou áudios com a possibilidade de **inserir** trilha e efeitos sonoros mais **elaborados, além da** composição de diferentes áudios, como entrevistas e/ou leitura de livros.
2. Descrição corrigida para o bloco de Vídeo: **Estão disponíveis diversos** serviços de vídeo: **Videoaula simples**, com apenas o interlocutor em plano **principal; Hand Drawn, uma animação** ilustrando a explicação da fala do narrador ou o próprio narrador escrevendo em tempo **real; Vídeo** Tutorial **explicativo, ensinando** passo a passo da utilização de uma ferramenta e/ou software, entre outros.
3. Descrição corrigida para o bloco de Texto: Visando a **transmissão** de conteúdo, os serviços de texto incluem a produção de cartilhas, manuais, panfletos e cartazes.
4. Descrição corrigida para o bloco de Imagem: **Precisando** de uma identidade visual, podemos providenciar **através dos nossos pacotes de criação** de logotipo, símbolo, paletas de cores, **marca d’água e padronagem.**
5. Descrição corrigida para o bloco de Mídia: Precisando de **auxílio** para a realização de eventos **virtuais** com live e interação do público, podemos fornecer as ferramentas e suporte para que seja isso seja possível.
6. Descrição corrigida para o bloco de Estúdio: Temos um estúdio equipado com uma infraestrutura **para** te ajudar **na** realização das suas produções **audiovisuais**.

- Nossa Newsletter: Fique por dentro de todas as novidades do programa e dos projetos que estamos **trabalhando.**
**Inscreva-se para receber periodicamente a nossa newletter em seu e-mail.** (Sugiro adicionar essa frase).

- Os “LINKS” no rodapé da página parece que não estão funcionando, pois retornam para o início da página.
- Corrigir "Email" para "E-mail".
- Corrigir em "Atuações": Passo **Fundo** (letra maiúscula).


 **PÁGINA '"IDEIAS"**
- Correção da frase inicial: Caso você tenha alguma **ideia**, crítica ou sugestão para melhorar **o nosso trabalho**, **compartilhe** conosco (e com toda a comunidade).


 **PÁGINA '"ACOMPANHAR SERVIÇOS"**
- Sugiro alterar "Acompanhe aqui seus serviços solicitados" para "Acompanhe aqui suas solicitações".
- Serviços solicitados **recusados** (tirar o R maiúsculo de Recusados).


 **PÁGINA '"SOLICITAR SERVIÇOS"**
- Na aba que abre para fazer a solicitação, colocar acento na palavra “Áudio” em todas as vezes que aparecem (nos exemplos 
do título e descrição e na caixa de seleção "Tipo de Serviço"), e também corrigir essa frase assim: "**Em** caso de dúvidas sobre os **tipos** de **serviços** do **PRACTICE, consulte** nosso site."

**_Revisão da parte dos "Serviços":_**
- Padronizar singular ou plural: por exemplo, está escrito: Áudio, Vídeos, Texto, Imagens, Mídia, Estúdio. Deixar tudo no singular ou tudo no plural (na minha opinião, poderia ser no singular).
- Cuidar para colocar ponto final no fim da descrição de cada serviço, pois alguns estão sem ponto ou com ponto e vírgula.
- Sobre os prazos de cada serviço, em todas as vezes está escrito “días” com acento agudo no i. Remover esse acento. Também poderia deixar ‘úteis” fora de parênteses. Exemplo: “7 dias úteis”.
- Onde não tem o prazo definido, poderia ser colocado: “Prazo: Variável”.
- Na seção de Vídeo, corrigir "Vídeo Aula Simples" para "Videoaula Simples".
- Na seção de Texto, fiz alterações no texto seguinte, além de remover “Obs:”: 
As solicitações dos serviços de texto precisam conter: **autor(es), título e subtítulo, imagens** e gráficos com **indicação da ordem** que serão apresentadas no texto, **referências** bibliográficas utilizadas **(dentro das normas ABNT)** **e, caso** seja necessário, licenças de direitos autorais das imagens utilizadas.
Orientações bem estabelecidas de design: **imagens** em boa resolução, **referências** de onde as imagens foram retiradas **e imagens** salvas em formato **JPEG**. 
- Na seção de Imagens, nos blocos "Identidade Visual Simples" e "Identidade Visual Completa", adicionar acento agudo na palavra “contém”, em ambos os blocos.
- Na seção de Mídia, a descrição está com ponto de interrogação no final. Alterar para um ponto final.
- Na seção de Estúdio, corrigir "infra-estrutura" para "infraestrutura".

São essas as correções textuais no momento. 
Além disso, o Mural ficou INCRÍVEL, parabéns a todos!! :heart_eyes:

**Comment by oraphaBorges** [comment]
@Dovyski por favor alterar manualmente no banco de dados na tabela de categorias, a categoria de "Audio" para “Áudio”. Após isso finalizar a issue.

**Comment by thaliafriedrich** [comment]
Vi agora que tenho que fazer uma correção do meu comentário anterior: onde eu coloquei "Inscreva-se para receber periodicamente a nossa newsletter em seu e-mail.", eu havia escrito errado ("newletter" em vez de "newsletter"), se puder, corrigir isso novamente, obrigada.

**Comment by oraphaBorges** [comment]
corrigido @thaliafriedrich

**Comment by oraphaBorges** [comment]
@Dovyski não precisa fazer a modificação no banco de dado, eu consegui fazer.

**Comment by oraphaBorges** [comment]
Revisão Textual Finalizada.
