### ISSUE TITLE
Adicionar tailwind aos estilos

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#279]
Para facilitar a edição de UI/UX, é muito interessante que o projeto tenha o [tailwind](https://tailwindcss.com/) integrado em sua lista de estilos.  O projeto [intranet](https://github.com/ccuffs/intranet) de CC faz uso dele, dá para ter uma ideia. Se eu não me engano, é so usar um `npm install` e colocar alguma coisa no `webpack.mix.js`.

**Comment by oraphaBorges** [comment]
LIb adicionada
