### ISSUE TITLE
Informar no mural que os serviços de cartilha e manual estão indisponíveis

### ISSUE THREAD

**Issue by alessandrapedrotti** [practice-uffs/web-feedback#281]
Conforme a [issue 74](https://github.com/practice-uffs/website-programa/issues/74#issuecomment-819524077) do repositório website, é necessário adicionar no mural também a informação de que os serviços de gravação em estúdio estão indisponíveis devido a pandemia e que os serviços de cartilha e manual estão indisponíveis. Pode ser adicionado uma tarja nesses serviços ou um aviso em cor diferente.

**Comment by CleissonVieira** [comment]
Implementar aviso de indisponibilidade e bloquear a opção do acesso a esses serviços.

**Comment by CleissonVieira** [comment]
Perfeito @alissonpeloso , ficou muito bom!


![image](https://user-images.githubusercontent.com/29258164/118610295-ff855080-b791-11eb-8f6d-8236ed3fba4b.png)
![image](https://user-images.githubusercontent.com/29258164/118610323-057b3180-b792-11eb-88ba-9cf10197c49c.png)
