### ISSUE TITLE
Editar respostas e excluir todos os serviços "teste"

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/web-feedback#283]
- Acredito que seria interessante se fosse possível editar as respostas que nós damos aos solicitantes, por motivos óbvios;
- Seria bom ter a opção de excluir alguns dos serviços para que eles não "poluam" a página. Nesse caso, falo dos vários testes que fizemos;
- Seria interessante poder utilizar a tecla enter para pular linhas nas respostas. E isso também deveria ser feito no texto de solicitação de serviço. Por exemplo na seguinte solicitação:

O vídeo de curta duração, gravado em estúdio sem slides. Será feito com 4 acadêmicas e cada um delas estará falando sobre a temática "Violência Fatal em Família", com duração de até 10 minutos. Será necessário na edição apresentar o logo do Laboratório de Tecnologias da Informação e Comunicação em Saúde (LATICS) + Logo da UFFS + Logo da UFCG. Coordenação: Dra. Silvia Carla Conceição Massagli. Roteiro: Dra. Silvia Carla Conceição Massagli. Nome das acadêmicas. Edição: PRACTICE. 

Isso tudo poderia ser dividido como foi pensado originalmente (quando falo originalmente, quero dizer que na descrição está dessa forma): 

O vídeo de curta duração, gravado em estúdio sem slides. Será feito com 4 acadêmicas e cada um delas estará falando sobre a temática "Violência Fatal em Família", com duração de até 10 minutos. 
Será necessário na edição apresentar o logo do Laboratório de Tecnologias da Informação e Comunicação em Saúde (LATICS) + Logo da UFFS + Logo da UFCG. 
Coordenação: Dra. Silvia Carla Conceição Massagli.
Roteiro: Dra. Silvia Carla Conceição Massagli.
Nome das acadêmicas.
Edição: PRACTICE

**Comment by amandasegattob** [comment]
Boa noite! Concordo com o @robisonjose, seria **muito** válido poder editar/excluir as respostas para os solicitantes!

**Comment by CleissonVieira** [comment]
Sobre os dois primeiros tópicos criei duas novas issues por motivos de organização.
Sobre o tópico que cita da possibilidade de quebra de linha com "enter"
Verifiquei que isso já é possível @robisonjose, ou compreendi errado a sua solicitação? Por favor, se estiver incorreto reabra a Issue e vamos conversar sobre. =D

**Comment by robisonjose** [comment]
@CleissonVieira 

![Captura de Tela (55)](https://user-images.githubusercontent.com/71669689/117218357-5a559a00-add9-11eb-96ac-f693f17e54a8.png)

![Captura de Tela (56)](https://user-images.githubusercontent.com/71669689/117218362-5cb7f400-add9-11eb-9e42-ce812dd58aef.png)

**Comment by CleissonVieira** [comment]
A quando a mensagem é enviada ele não fica com o entender. Entendi agora hehe Obrigado!
