### ISSUE TITLE
Ordem dos serviços solicitados

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/web-feedback#284]
Eu não entendi a ordem que os serviços solicitados aparecem, acredito que seja por ordem de chegada. No entanto, seria mais interessante que a ordem fosse por "ultima atualização" de maneira decrescente, isto é, as solicitações que estão sem atualizações a mais tempo devem aparecer primeiro.

**Comment by CleissonVieira** [comment]
Nova issue criada para implementação de filtro para solicitações a partir da #287: #289

Se acaso me equivoquei pode reabrir a issue.
