### ISSUE TITLE
Problemas no tipo de serviço

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/web-feedback#286]
(relacionado a remover duplicadas visto na issue anterior)

** Descreva o bug/problema **
Uma solicitante informou que não conseguiu pedir uma live pois não conseguiu selecionar nada no campo "Especificação do serviço". 

** Capturas de tela **

![Captura de Tela (41)_LI](https://user-images.githubusercontent.com/71669689/115585644-2db26600-a2a2-11eb-90a3-1baf381d718b.jpg)
![Captura de Tela (42)](https://user-images.githubusercontent.com/71669689/115585655-2ee39300-a2a2-11eb-9f83-7e0f241c8371.png)

** Desktop (o meu, não sei o da solicitante): **
  - Sistema operacional: [Windows]
  - Navegador [Chrome]
  - Versão [Versão 89.0.4389.128 (Versão oficial) 64 bits]

**Comment by oraphaBorges** [comment]
@Dovyski este é um problemas apenas do ambiente de produção.

**Comment by CleissonVieira** [comment]
Problema relacionado na issue #335
