### ISSUE TITLE
Anexos, divisão de serviços e notificações

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/web-feedback#287]
- Acredito que seria interessante ter a opção de colocar anexos em nossas conversas. Isso torna a comunicação mais fácil e direta; (no momento utilizar opção do drive - Clei comment)

- Seria bom se tivesse uma divisão por tipo serviço na parte dos serviços. Da forma que está fica tudo meio misturado. Quando tem poucos serviços não é um problema, mas quando tiver muitos vai ser ruim para se organizar. A ideia inicial seria organizar por equipes; (fazer paginação e filtro - comment Clei)

- Seria interessante ter um tipo de notificação visual para quando a solicitação tem uma nova mensagem. (prioridade - comment Clei)

**Comment by luizatonial** [comment]
ACHO MUITO IMPORTANTE ter como filtrar/dividir as solicitações por equipe ou categoria do serviço

**Comment by CleissonVieira** [comment]
Pessoal, criei duas novas Issues para uma melhor divisão e organização das tarefas. 
Sobre a opção de inserir anexos nas conversas, no momento vamos deixar para ser discutido entre todos, quem sabe em uma reunião, pois no momento utilizamos o google drive como forma de armazenar todos os arquivos pertinentes ao PRACTICE, se tornando uma forma de histórico. 

No momento vamos manter assim e quando necessário compartilhar uma pasta no drive da solicitação ao solicitante.
