### ISSUE TITLE
Criar opção para excluir comentários em solicitações

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#291]
Issue criada a partir de um tópico da issue #283 

Hoje, a partir do momento que enviar um comentário, não é possível editar o excluir a mensagem dentro de uma solicitação.

**Objetivo:** Criar opções em comentários com botão excluir a mensagem.

**Comment by stefanimeneghetti** [comment]
Opção de exclusão criada

![Tela com botão de exclusão](https://user-images.githubusercontent.com/51202548/118894989-acb7b000-b8db-11eb-824f-ba3a0b31d7bf.png)
