### ISSUE TITLE
Melhoria para campo text

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#293]
Issue criada a partir da #283 

Hoje quando utilizado `enter` para quebra de linha ao escrever um comentário em solicitações e ideias do Mural, ao enviar esses comentários as quebras de linha são ignoradas.

**Objetivo:** fazer com que as quebras de linha sejam enviadas no comentário.

![image](https://user-images.githubusercontent.com/29258164/117368402-de6f5680-ae99-11eb-86a9-e83595acc5e6.png)

![image](https://user-images.githubusercontent.com/29258164/117368393-d9aaa280-ae99-11eb-91b2-042e2146b181.png)

**Comment by GuilhermeGraeff** [comment]
Estou tentando arranjar uma maneira de rodar o web-feedback em meu computador, aceito sugestões de tutorial para que consiga fazer isso.
Uma possível solução talvez seria utiliazar a tag <pre></pre>, assim que conseguir rodar o projeto vou tentar usar essa tag.

**Comment by GuilhermeGraeff** [comment]
Eu fiz um pull request com o problema corrigido teoricamente, perdoem-me se eu cometi algum erro na descrição do pull request, valeu!

**Comment by oraphaBorges** [comment]
@GuilhermeGraeff Aceitei o PR e ta funcionando bonitinho. Gostaria de deixar uma sugestão, que é tirar da tag <p> o style, e criar uma classe de CSS lá no fim da página onde ficaram o css, exemplo:
```
<p class="text-pre-wrap">{{comment.text}}</p>
```
```
<style scoped>
.card{
    margin: 15px;
}
.text-pre-wrap{
    white-space:pre-wrap
}
</style>
```

assim mantem as boas práticas e se houvesse algum outro campo nesse mesmo componente que fosse usar esse CSS faria a reutilização.

**Comment by CleissonVieira** [comment]
Perfeito @GuilhermeGraeff 
Testei o comentário com as quebras de linha e funcionou perfeitamente!! ><

![image](https://user-images.githubusercontent.com/29258164/118609838-88e85300-b791-11eb-986c-dac5f53975ee.png)
