### ISSUE TITLE
Modelo para notificações via e-mail

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#302]
@practice-uffs/con-design  @practice-uffs/con-conteudo @Claudineia-VR 

Olá pessoal!

Preciso de uma ajuda de vocês.
Está sendo concluída a implementação do envio de notificações por e-mail conforme é realizado interações em solicitações do Mural. Issue #290

Essas notificações são e-mails, portanto precisa ser desenvolvido um padrão para as mesmas. As notificações são:
- Envio de e-mail para solicitante após sua solicitação receber uma interação da parte do PRÁCTICE;
- Envio de e-mail para atendente após solicitante realizar uma interação no serviço que está realizando atendimento;

Vamos montar juntos esses dois padrões de notificações, o quanto antes, para informar no código de implementação dessas notificações. Marquei a equipe de Design e de Conteúdo pois esse e-mail enviado pode conter texto e imagem.

**Comment by GessicaZanon** [comment]
@CleissonVieira sabe me dizer onde está o documento para fazer a escrita desses e-mails?

**Comment by GuilhermeGraeff** [comment]
O html que eu desenvolvi ficou assim:
![Practice_Email_Template](https://user-images.githubusercontent.com/48657331/119283210-aba3bd00-bc12-11eb-9784-51ba7b9af9d4.png)
Acho que era essa a ideia geral do template né?

**Comment by CleissonVieira** [comment]
@oraphaBorges como você está com a issue relacionada aos e-mail, sendo a #290, quais as possibilidades para o @GuilhermeGraeff ajustar conforme a biblioteca que você está utilizando para envio de e-mail do Laravel aceita?

**Comment by GuilhermeGraeff** [comment]
Este é o link para o modelo html que eu criei para o envio de e-mail (sem nenhuma integração com o Laravel): [https://guilhermegraeff.github.io/modeloemail/solicitado](url), @practice-uffs/con-design gostaria de saber se este modelo é apropriado e se é necessário fazer alguma alteração.

**Comment by isabelirk** [comment]
Boa tarde,

Conforme o solicitado, montei as mensagens automática. Peço que verifiquem se está de acordo com a ideia proposta. Adicionei uma sugestão para os casos em que o solicitante criar uma solicitação no mural, e nesse caso recebera uma confirmação da conclusão da solicitação por e-mail. Segue abaixo:

**Envio de e-mail para solicitante após sua solicitação receber uma interação da parte do PRACTICE.**
Prezado(a) {nome do solicitante},
Informamos que um integrante da equipe PRACTICE retornou na sua solicitação {título da solicitação}. Para mais informações acesse o link: https://mural.practice.uffs.cc/.
Atenciosamente, equipe PRACTICE.
ESTA É UMA MENSAGEM AUTOMÁTICA. POR FAVOR, NÃO RESPONDA!

**Envio de e-mail para atendente após solicitante realizar uma interação no serviço que está realizando atendimento.**
Prezado(a) {nome do atendente},
Informamos que o/a solicitante {nome do solicitante} realizou um novo comentário na solicitação {título da solicitação}. Para mais informações acesse o link: https://mural.practice.uffs.cc/.
Atenciosamente, equipe PRACTICE.
ESTA É UMA MENSAGEM AUTOMÁTICA. POR FAVOR, NÃO RESPONDA!

**(sugestão) Envio de e-mail após o solicitante criar uma nova solicitação no mural.**
Prezado(a) {nome do solicitante},
Informamos que a sua solicitação {título da solicitação} foi cadastrada com sucesso. Você receberá uma resposta da equipe do PRACTICE em até três dias úteis. 
Atenciosamente, equipe PRACTICE.
ESTA É UMA MENSAGEM AUTOMÁTICA. POR FAVOR, NÃO RESPONDA! 

@mariagelain poderia verificar também.
Atenciosamente.

**Comment by morgana-mo** [comment]
> O html que eu desenvolvi ficou assim:
> ![Practice_Email_Template](https://user-images.githubusercontent.com/48657331/119283210-aba3bd00-bc12-11eb-9784-51ba7b9af9d4.png)
> Acho que era essa a ideia geral do template né?
> Ainda tem algumas coisas para refinar e ver como é a comunicação do Laravel com o envio dos e-mails para ver se tá tudo certinho.

Gostei da versão que você desenvolveu, mas acredito que precisamos padronizar esse design
1- Utilizar uma mesma família de ícones das redes sociais (ou todos preenchidos ou todos com apenas traçados)
2- Colocar os ícones de acordo com a ordem alfabética (Instagram,Facebook,Twitter, YouTube)

**Comment by TaynaraCh** [comment]
Concordo com a Morgana, olhei na pasta de id visual e são apenas essas as opções disponíveis, acho melhor criamos variações preenchidas e também vazadas para serem utilizadas de maneira padrão a depender da necessidade, vou criar uma issue para ajustar isso!

**Comment by CleissonVieira** [comment]
@TaynaraCh por gentileza, assim que finalizarem a Issue 611 no programa informar nesta que foi concluída, assim quem está incluso consegue dar continuidade com base nos novos modelos de ícone para então chegar a uma conclusão desta issue.

Agradeço desde já!

**Comment by TaynaraCh** [comment]
Prontinho! Está na [pasta](https://drive.google.com/drive/u/0/folders/10lDb0JiGo-WOBER_yZXtsOw4kMym61sR) de saída da issue [#611](https://github.com/practice-uffs/programa/issues/611). Ainda não possuo autorização para mexer na pasta de identidade visual do programa, assim que conseguir irei adicionar lá também.
Se precisar de alguma coisa é só chamar, ok?

**Comment by CleissonVieira** [comment]
Perfeito pessoal, muito obrigado a todos pela participação!
Os templates foram criados e estão prontos para utilizar nos e-mails de notificação.
