### ISSUE TITLE
Implementação de escolha de prazo final para entrega de produto

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/web-feedback#305]
Temos percebido que as solicitações que chegam para o @practice-uffs/con-midia não apresentam uma descrição clara do prazo que o solicitante deseja para que seja feita a entrega final do produto (especificamente vídeos), o que torna a comunicação mais trabalhosa, uma vez que é necessário perguntar ao cliente para quando é o material, aguardar resposta e, só então, analisar a viabilidade.

Pensamos na possibilidade de haver uma opção, no momento da solicitação de serviço, onde o usuário pode selecionar um prazo final para a entrega. Contudo, para nós do mídia, esse prazo não pode ser menor que dez dias úteis - já pensando naqueles 3 dias de avaliação de demanda e no mínimo 7 para conseguir atende-la.

Claro, esse prazo pode ser maior, ex.: 10, 15, 20 dias...

**Comment by CleissonVieira** [comment]
@GuilhermeGraeff da para adicionar um campo ao item onde o solicitante seleciona uma data, essa data o próximo valor (dia) a ser selecionado vai ser 10 dias após o dia atual onde de criação da solicitação. 
Após esses 10 dias todos são liberados.

**Comment by CleissonVieira** [comment]
@alissonpeloso Vou pedir para você trabalhar em conjunto com o Guilherme nessa tarefa, ele informou estar com dificuldades, caso não consigam por favor não exitem em solicitar auxilio para o Raphael e para mim.

**Comment by CleissonVieira** [comment]
Revisei as implementações em código, ao meu ver estão ok.
Muito bem pessoal!
Finalizando a issue por questões de organizações, porém PRs ainda não aceitos, itens a ser conversado em reunião por problemas de merge.
