### ISSUE TITLE
[BACK] Criar seeders para Categoria e para Local

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#31]
Criar [seeders](https://laravel.com/docs/7.x/seeding) para a Categoria e para o Local (ambos utilizados na criação/edição de um item).

**Comment by Dovyski** [comment]
Ainda não temos bem definido o que cada um será. Para termos algo, vamos usar o seguinte:

* Locais: os campi da UFFS
* Categorias: "Ideia", "Serviço", "Crítica".
