### ISSUE TITLE
Redirect na tela de admin a partir da edição de uma solicitação

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#310]
Hoje se estou na tela de Admin e edito um serviço, após editar sou direcionado para tela de "Acompanhar Solicitação".

**Objetivo:** após um admin editar um serviço ser direcionado para página principal de admin.

**Comment by CleissonVieira** [comment]
Perfeito Alisson, ótimo trabalho. Revisei o código!
Por questões de organização finalizo está issue.

Merge será feito após reunião do dev.
