### ISSUE TITLE
Aviso de que uma tarefa está em análise

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#311]
Na listagem de pedidos do cliente, se a solicitação não tem um link do github preenchido, mostrar um aviso proeminente informando que o pedido está em análise (e não em produção).

**Comment by CleissonVieira** [comment]
Hoje é possível vincular uma issue do github a solicitação, exemplo:

![image](https://user-images.githubusercontent.com/29258164/120517217-9a8f4480-c3a6-11eb-9fce-eed1664eb095.png)

![image](https://user-images.githubusercontent.com/29258164/120517259-a8dd6080-c3a6-11eb-9e86-db58baf0ee52.png)

**Objetivo:** Se esse vínculo não existir então informar que está em analisa com uma tag.
Essa tag precisa estar presente na listagem de solicitações e também quando a mesma é acessada. 

Um lindo esboço de exemplo:

![image](https://user-images.githubusercontent.com/29258164/120517724-230de500-c3a7-11eb-8f8b-5067cee7e92f.png)

![image](https://user-images.githubusercontent.com/29258164/120517828-3e78f000-c3a7-11eb-95cb-d84e6c6e05e7.png)


Sabemos que a categoria "Aguardando aprovação" já existe, porém se vê necessário essa tag.

**Comment by stefanimeneghetti** [comment]
Tags criadas:

![Captura de tela de 2021-06-08 10-28-56](https://user-images.githubusercontent.com/51202548/121196202-a8c9de80-c846-11eb-9f9f-3413c1d009b1.png)

![Captura de tela de 2021-06-08 10-28-39](https://user-images.githubusercontent.com/51202548/121196219-acf5fc00-c846-11eb-8fb2-528018c347dc.png)

As tags seguem a nomenclatura e cores solicitadas e foram atribuídas às solicitações seguindo os seguintes critérios:
  - Caso uma solicitação **possua** o link de uma issue ela recebe uma das quatro tags possíveis de acordo com seu status
  - Caso a solicitação **não possua** o link de uma issue ela recebe a tag "Em análise" a menos que a mesma possua status "recusado" (neste caso a solicitação recebe a tag "Recusado").

**Comment by CleissonVieira** [comment]
Código revisado. Ótimo trabalho Stefani, ficou ótimo.
Issue finalizada para manter organização.
Merge ainda não realizado pois será conversado em reunião sobre as operações de merge.
