### ISSUE TITLE
Prazo esperado

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#312]
Criar um campo novo na solicitação de serviço (do tipo texto) onde o cliente pode informar qual é o prazo esperado para a conclusão do pedido. Por exemplo, informar `10 dias`, etc.

Isso ajuda a equipe a estimar a quantidade de trabalho  prontamente cancelar um pedido que não tenha como ser cumprido.

**Comment by CleissonVieira** [comment]
Essa mesma tarefa está dentro da issue #305 
Por esse motivo estou finalizando essa
