### ISSUE TITLE
Alteração enunciado demandas

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/web-feedback#314]
Enunciar as demandas por categoria e não pelo título, muitas vezes os solicitantes colocam o mesmo título em mais de uma demanda, criando confusão para a triagem das demandas, além da separação das demandas por equipe, o que diminuiria a poluição visual do mural.

Ex.: 
- Título do pedido: Transmissão ao vivo dia XYZ / Tipo de serviço: Transmissão ao vivo
- Título do pedido: Transmissão ao vivo dia XYZ / Tipo de serviço: Transmissão ao vivo

Em caso de dúvidas, ficamos a disposição.

**Comment by CleissonVieira** [comment]
Com a issue #289 essa questão se resolve. 
Dessa forma vai existir opções de filtros.
