### ISSUE TITLE
Melhorar UX/UI da página "Solicitar Serviços"

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#315]
Hoje para o usuário vizualizar todos os serviços (com breve descrição) do PRACTICE da página de [Solicitar Serviços](https://qa.mural.practice.uffs.cc/servicos/solicitar) é necessário rolar o scroll todo para baixo, sendo uma experiência ruim para o usuário, e com possibilidade dos serviços se expandirem e esse scroll se tornar aqui maior.

**Objetivo:** Alterar o layout da listagem dos serviços de forma que quando o usuário clica em uma tipo de serviço (tipo: Áudio, Vídeo, etc) renderize apenas os serviços selecionado.

Minha ideia seria usar o mesmo layout dos cards atuais, porém diminuindo para mostrar 4 por linha e não 3, sendo estes os cards: 
![image](https://user-images.githubusercontent.com/29258164/119918400-c0e45880-bf3e-11eb-97d1-9a154d717628.png)

**Os exemplos abaixos são modelos prontos do template que já utilizamos.**
[**Clique aqui para acessar o template e sua documentação**](https://bootstrapmade.com/demo/FlexStart/)

Da para utilizar esse stylo:
Sendo "All", "APP", "CARD" e "Web" os serviços, como se fosse "Áudio", "Vídeo", etc.

![image](https://user-images.githubusercontent.com/29258164/119922144-98139180-bf45-11eb-90f2-3b2149f0e89d.png)

Outro exemplo é este:
Onde fica igual o netflix, existe os serviços um em baixo do outro, porém os sub serviços é utilizado scroll lateral.

![image](https://user-images.githubusercontent.com/29258164/119922452-330c6b80-bf46-11eb-9906-fa4a8862f502.png)

Fica livre para utilizar da criatividade, acima são apenas exemplos.

**Comment by stefanimeneghetti** [comment]
Utilizei a primeira opção apresentada e acabei mantendo apenas três cards por linha pois achei que ao colocar quatro eles acabavam ficando muito finos.

![Nova página de seleção de serviços](https://user-images.githubusercontent.com/51202548/120222798-ea3f0600-c216-11eb-91c7-a44dab4e2ddc.png)

**Comment by CleissonVieira** [comment]
Revisada e demonstrada durante reunião
