### ISSUE TITLE
Mural Versão 2.0

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#318]
**Issue** direcionada a entender o fluxo de cada área de solicitação (Áudio, Vídeo, Texto, etc) com objetivo de uma nova versão do Mural. 

Preciso que cada líder, em forma de comentário, informe o fluxo atual que seus solicitantes precisam seguir para solicitar um serviço hoje. Em uma segunda parte do comentário informe qual seria o fluxo ideal, quais ferramentas necessárias, para criar e adaptar uma nova versão.

É necessário o fluxo completo e bem detalhado para que a equipe de dev consiga levantar todos os requisitos a serem implementados e identifique o melhor cenário.

@practice-uffs/lideres 

**Abaixo uma lista de alterações / implementações para o Mural V2:**

- [x] NEW: Pesquisa de satisfação (enviada por e-mail e com possibilidade de responder na solicitação)
- [x] NEW: painel de admin com função para atribuir e retirar permissão de admin
- [x] NEW: possibilidade de criar ou atribuir enquetes/formulários dentro de solicitações
- [x] REFACTOR - Alterar / melhorar caixa de comentário, onde seja completa: com possibilidade de parágrafo, informar links, inserir quebra de linha, etc.

**Comment by morgana-mo** [comment]
Olá, eu já havia comentado com a @TaynaraCh e lembro que o @robisonjose também já tinha comentado a um tempo atrás do Mural ter uma funcionalidade que indique uma espécie de "bandeira" em que o sistema está operando para atender um determinado tipo de serviço (ex: Identidades visuais, edição de vários vídeos), ou até mesmo algo como "seu serviço está na fila e por termos várias demandas similares ele pode demorar x dias para começar a ser atendido. Porque eu tenho percebido que os solicitantes aparecem de uma vez pedindo "n" coisas muito parecidas e depois fica um tempo sem essa demanda voltar.  Não sei se isso é possível mas para as equipe de Design e Mídia iria facilitar muita coisa nos próprios atendimentos do Mural

**Comment by TaynaraCh** [comment]
Fluxo de Identidades Visuais

- Solicitante pede se é possível realizar o serviço> se sim, enviamos um formulário para saber o que ele quer> iniciamos a produção do logotipo> enviamos uma entrega intermediária com duas ou três opções de logotipo/paleta de cores/tipografia> solicitante retorna com uma esolha e/ou com pedidos de ajustes na esolha> finalizamos a arte e criamos o restante dos elementos (marca d'água, padrão)> enviamos o logotipo e etc em formato png e uma descrição em pdf> acontece do solicitante retornar novamente pedindo alguma alteração no que foi produzido posteriormente ao envio intermediário, analisamos se é viável ou não relaizar> se sim, enviamos novamente os arquivos com os ajustes

Fluxo de artes em geral (divulgação de eventos, anúncios...)

- Solicitante faz o pedido> é encaminhado um formulário> são produzidas algumas opções> é enviado ao solicitante> ele retorna com uma escolha e solicita ou não alguns ajustes> ajustes são realizados> o envio final é realizado (as vezes acontece do ciclo se repetir várias vezes, vai e volta até que o cliente aprove definitivamente)

Espero que tenha conseguido entender! Qualquer cosia eu explico novamente kkk

**Comment by MilenaPaz2020** [comment]
![Fluxo Lives](https://user-images.githubusercontent.com/71154460/124511730-33055400-ddad-11eb-8683-ed759fbaafa2.png)
Fiz um breve esboço de como tem sido o fluxo e comunicação para o atendimento das lives. Algo que atrasa/atrapalha é as informações incompletas dos solicitantes (sem saber data e horário de live, por exemplo, não conseguimos avaliar corretamente a disponibilidade de atendimento).

O ideal é que no momento da solicitação seja informado data e horário, mais ideal ainda seria de na própria solicitação fosse possível preencher o formulário e protocolo cerimonial do evento.

**Comment by MilenaPaz2020** [comment]
![Fluxo vídeos](https://user-images.githubusercontent.com/71154460/124512297-67c5db00-ddae-11eb-8692-a5df1a0dcc3e.png)
Novamente, apenas um esboço, que tenta resumir o fluxo de trabalho e comunicação para demandas de edição. O que tem nos atrapalhado e atrasado é quando os solicitantes não esclarecem o que querem para a edição ou enviam um roteiro sem nexo.

Ex: Editamos conforme o que está no roteiro, o produto é enviado ao cliente que responde encaminhando imagens, ide visual, música que não foram antes solicitadas, ocasionando retrabalho.

O ideal seria que as informações e roteiro fossem encaminhadas no momento de fazer a solicitação, pouparia muito tempo.

Desculpa pela demora em comentar.

**Comment by morgana-mo** [comment]
Olá!
Lembrei que em alguns emails alguns solicitantes apontaram a necessidade de que fosse adicionada nas opções de localização a `Reitoria` tendo em vista que alguns setores estão lá localizados.

**Comment by CleissonVieira** [comment]
Revisei todos os fluxos aqui comentado, e todos são possíveis realizar no Mural V2. 
Muito obrigado pessoal pela atenção e informações aqui escritas!! <3

A versão 2 do Mural será concluída então.

Só precisa tirar uma dúvida com @morgana-mo , pois não entendi esse último comentário sobre localização a Reitoria.
Quais opções de localização?

**Comment by morgana-mo** [comment]
Bom dia Cleisson, já está contemplado na versão disponibilizada pra a gente testar
![Captura de Tela (307)](https://user-images.githubusercontent.com/71781124/130229587-78fa88d9-f99a-46a1-8433-85a2d332e647.png)
