### ISSUE TITLE
Acrescentar informações da ultima pessoa a ter comentado na solicitação

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/web-feedback#320]
Hoje na listagem de solicitações, na tela de admin, temos a informação de data e hora da última atualização feita. 

![image](https://user-images.githubusercontent.com/29258164/120230923-b2d85580-c226-11eb-975a-9f887683eef7.png)

**Objetivo:** além da data e hora precisa ser incluso quem foi o usuário que realizou essa última interação dentro da solicitação.

**Comment by GuilhermeGraeff** [comment]
Agora eu fiquei na dúvida se sou eu que coloco o "_Review in progress_" assim que eu envio o PR ou os revisores.

**Comment by Dovyski** [comment]
Tu pode colocar review em progress quando enviar o PR, sem problema, @GuilhermeGraeff

**Comment by CleissonVieira** [comment]
A atividade foi concluída, porém é necessário verificar o problema ao dar merge com Fernando.
Finalizando por vias de organização
