### ISSUE TITLE
Disponibilizar todos os pontos de API através de /api/

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#4]
O sistema terá interação com o aplicativo móvel do practice, então todos os dados precisam estar disponíveis para leitura através do endpoint `/api/`. Essa tarefa está relacionada à criação da base para que essa API comece a funcionar.

Depende de #5, #14 e #17.

**Comment by JeanCHilger** [comment]
Esta issue depende de outras, e portanto ainda não foi completada. A API para o `Item` já estava pronta, mas em um *merge* acabei sobreescrevendo as alterações, futuramente, portanto, ela deverá ser refeita juntamente com as demais dependências.

Irei tirar o meu *assign* caso alguém queira pegar esta *issue*.
