### ISSUE TITLE
Alterar ícone Practice Mural

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/web-feedback#432]
Alterar logo do mural com essas novas: [LINK](https://drive.google.com/drive/folders/1hGKBrAAI6jMsl_i2l7oH4xi4s8MZPhAE)

**Comment by CleissonVieira** [comment]
@alissonpeloso  Ao testar o ícone do login tive o seguinte erro após Aceite do PR do limite de login:
![image](https://user-images.githubusercontent.com/29258164/156971347-62f8312d-042d-4e78-99c5-282b7bcc313c.png)
![image](https://user-images.githubusercontent.com/29258164/156971368-55d2c254-044f-4c82-9df9-c269548cfdf5.png)

Vou aguardar correção para corrigir a branch e abrir PR da tarefa 
![image](https://user-images.githubusercontent.com/29258164/156971134-2cb8b9e8-89fc-45d8-b1a6-71268d12e31a.png)

**Comment by alissonpeloso** [comment]
Acredito que só faltou você adicionar essas duas variaveis no `.env`, assim como descrito no PR e também explicido no `.env.example`.

![image](https://user-images.githubusercontent.com/51202705/157021427-ff26295e-3cb0-4d6b-ad89-d6949393bbd0.png)

Tenta settar essas variáveis e testar

**Comment by CleissonVieira** [comment]
Perfeito, desculpa, foi falta de atenção minha.
Setei de funcionou perfeitamente, vou realizar o PR
