### ISSUE TITLE
[FRONT] Substituir view items/

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#49]
Substituir a dashboard HOMER por uma feita manualmente (ou outra mais modificável). A nova dashboard deve disponibilizar as mesmas funcionalidades da HOMER.

Não foi possível personalizar a dashboard, de modo que esteja de acordo com as demais seções, bem como satisfazer à issue #16.

**Comment by Dovyski** [comment]
Eu posso dar uma olhada nessa issue. Alguma informação do porque a dashboard do HOMER não teve êxito na personalização?

**Comment by JeanCHilger** [comment]
Nós conseguimos editar apenas as cores, questão de *paddings*, sombras e demais opções não encontramos nenhuma forma de estilizar. Isto faz com que o estilo da página `/items` fique diferente das demais, parecendo que não pertence ao todo. Além disso o HOMER usa bulma e nós optamos por utilizar materialize, isso eleva ainda mais a diferença visual.

Acreditamos que fazer algo semelhante do zero não seja tão trabalhoso, deixamos esta issue parada por um tempo pois o funcionamento estava ok, mas como vamos realizar diversas modificações optamos por avançar nisto.

**Comment by JeanCHilger** [comment]
A issue #76 foi resolvida pela PR #81. Quanto a esta issue, resta algumas questões sobre funcionalidades presentes no HOMER:

1. A busca por itens será feita apenas selecionando a categoria desejada (como nos _wireframes_), ou haverá um campo para busca textual?;
2. Alternar entre temas _dark_ e _light_ será uma funcionalidade necessária?
3. Alternar entre listagem horizontal ou em formato de grid será uma funcionalidade necessária?

**Comment by Dovyski** [comment]
> A issue #76 foi resolvida pela PR #81. Quanto a esta issue, resta algumas questões sobre funcionalidades presentes no HOMER:
> 
> 1. A busca por itens será feita apenas selecionando a categoria desejada (como nos _wireframes_), ou haverá um campo para busca textual?;

Em um primeiro momento, apenas uma seleção por categoria (como nos _wireframes_).

> 2. Alternar entre temas _dark_ e _light_ será uma funcionalidade necessária?

Não. Acho que podemosa manter o tema _light_ por enquanto e, no futuro, se sentirmos que queremos ser super cool, habilitamos o dark (e o trabalho que isso demanda)

> 3. Alternar entre listagem horizontal ou em formato de grid será uma funcionalidade necessária?

Sim.
