### ISSUE TITLE
Usuário postar um feedback/pedido

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#5]
Depende de: https://github.com/practice-uffs/web-feedback/issues/2

Implementar a página básica onde usuários possam interagir com um formulário que tenha os seguintes campos:

- Tipo (dropdown com: Sugestão, Crítica, Ideia, Reclamação, Medos e comentários
- Visibilidade: pública (todos que visitem o site podem ver) ou privada (não listada, somente a equipe PRACTICE pode ver).
- Descrição (texto com no máximo 800 caracteres)
- Nome
- Função (Docente, Discente, TAE, comunidade externa)
- E-mail do usuário

O elemento `Project` ([controller](https://github.com/ccuffs/tccr/blob/master/app/Http/Controllers/ProjectController.php) e [modelo de banco de dados](https://github.com/ccuffs/tccr/blob/master/app/Project.php)) do projeto [tccr](https://github.com/ccuffs/tccr) já tem isso implementado. Precisa apenas alterar os campos e os formulários.

**Comment by JeanCHilger** [comment]
**Dúvidas:**

1. O usuário precisa estar logado para realizar um pedido, certo?;
2. Se sim, o nome de usuário pode ser obtido apartir do usuário logado? (e-mail e função acredito que não possam)

**Comment by Dovyski** [comment]
Não está claro mesmo, pode ficar tranquilo 😉 

O sistema deve permitir duas coisas principais: a) controle de ideias (um texto para que todos os usuários saibam da ideia e possam discutir ou reagir a ela), b) controle de serviços  (um serviço é um pedido que o usuário/cliente faz ao PRACTICE, solicitando que algo seja feito).

A ideia não tem um ciclo de vida propriamente dito. O usuário posta a idea, outros usuários podem ver ela (se for pública), comentar, reagir, etc.

Um serviço tem um ciclo de vida. Ele contém quem pediu e o que precisa ser feito. Ele muito provavelmente será integrado com o fluxo de trabalho das equipes via issues no futuro. Por enquanto, precisamos apenas que um serviço seja criado e tenha seu status alterado (criado, em andamento, cancelado, etc).


Para agilizar o dev, eu modelei tudo como sendo um item. Logo, uma ideia, comentário da ideia, reação da ideia, ou serviço é um item. O `parent_id` do `Item` indica essa relação. Um Item do tipo `comentário` com `parent_id` igual a `12`, por exemplo, significa que essa entrada no banco é um comentário do Item de id `12` (seja ele uma ideia, serviço, etc).

Ficou mais claro?

**Comment by JeanCHilger** [comment]
Sim, agora entendi. 

Quanto ao serviço, haverá restrição de quais usuários podem pedir serviços, ou então um sistema onde serviços podem ser aceitos ou rejeitados pela equipe do practice, ou por enquanto o funcionamento seria semelhante ao do `Item` (sem esse tipo de controle no caso)?

**Comment by Dovyski** [comment]
Qualquer um poderá pedir serviço, mas no futuro teremos um sistema de moedas virtuais para priorizar o que fazer. Acho que agora é mais tratar serviços sem qualquer tipo de controle.

**Comment by JeanCHilger** [comment]
A *view* `items.create` (já criada) tem características semelhantes às descritas aqui, seriam elas a mesma coisa (neste caso a view seria apenas adaptada até então eu estava tratando um item como um elemento individal, mas pelo que entendi, o `Item` seria um objeto abstrato, enquanto Feedback e Serviço utilizariam as características de `Item` mas de formas mais especializadas, seria isso?).
