### ISSUE TITLE
[Discussão] Usar a mesma view para serviço e para feedback

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#63]
As *issues* descrevendo as funcionalidades de feedback (#5) e de serviço (#17) são muito semellhantes, e a *view* `items.create` já está criada, atendendo a maioria delas. A ideia é utilizar a mesma *view* (e consequantemente *controller*) para ambas as funcionalidades, e como eu farei a #5 e o @arufonsekun está fazendo a #17, acho interessante levantar uma discussão sobre como poderíamos aproveitar os recursos.

**Comment by JeanCHilger** [comment]
A minha ideia seria modificar o método `create` de `ItemsController`, de forma a possibilitar a passagem de um argumento. Este argumento controlaria o tipo: `1` para feedback e `2` para serviço. Essa informação seria passada para a *view* `items.create`, e os ajustes específicos para cada tipo seriam feitos lá.

**Comment by Dovyski** [comment]
Essa ideia do @JeanCHilger é ótima. Pode implementar ela.

**Comment by arufonsekun** [comment]
Também concordo que a gente deva implementar desse jeito. Só estou com uma dúvida em relação ao campo `categoria`. Ele deve aparecer caso o usuário criar um serviço, pois atualmente as opções para esse campo são: Ideia, Critica e Serviço.

**Comment by JeanCHilger** [comment]
Acredito que este campo não esteja relacionado com a categoria interna do `Item`, e sim com a categoria definida pelo usuário no momento da criação. Haverão categorias distintas para `Feedback` e `Serviço`, para implementar isto alguns ajustes no modelo `Category` devem ser feitas. Por hora não vamos considerar isto, numa issue futura, implementamos isto.

**Comment by arufonsekun** [comment]
blz

**Comment by JeanCHilger** [comment]
A discussão já foi encerrada, e portanto a issue será fechada.
