### ISSUE TITLE
[BACK: Item] Alterar modelo Category

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#65]
O modelo `Category` deve ser alterado, adicionando um campo `item_type` (ou algo do tipo, este é apenas um exemplo), permitindo que hajam categorias distintas para `Feedback` e `Serviço`.

O *seed* `CategorySeeder` precisa ser modificado de acordo. Por enquanto vamos utilizar os seguintes valores:
- Para `Feedback`: Sugestão, Crítica, Ideia e Reclamação;
- Para `Serviço`: Modificação, Nova Funcionalidade; (como comentado pelo @Dovyski, futuramente poderá haver integração com o sistema de *issues* do github, e portanto acho que seria interessante que as catogorias de `Serviço` fossem semelhantes às *labels* das *issues*).

Após isso basta alterar o método `items.create` para filtrar a categoria.

**Comment by Dovyski** [comment]
Eu gosto bastante da ideia de colocar um `item_type` na `Category`, acho que podemos seguir por esse caminho. Dessa forma, no controller do `Item`, podemos filtrar as categorias pelo tipo (`type`) do item em mãos.
