### ISSUE TITLE
Trying to get property 'reactions' of non-object

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#66]
Depois de fazer um checkout do código, e init do banco, incluindo os seeders, ao acessar `items/create` o seguinte erro acontece:

![image](https://user-images.githubusercontent.com/512405/88587107-cc6ba800-d02b-11ea-8e0e-7f73927d9cfd.png)

**Comment by JeanCHilger** [comment]
Isso ocorre pois a rota `items/create` foi desabilitada, agora ela é acessada via `items/create/{type}`, onde `type` define se o item é um feedback ou um serviço. Mas de fato, deveria estar mostrando um 404, isto será corrigido.

**Comment by Dovyski** [comment]
Ok, vou fechar a issue então. Provavelmente resolveremos isso no futuro via UI, então não precisamos nos preocupar agora.
