### ISSUE TITLE
Implementar view /items

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#7]
Nessa página qualquer usuário (ou visitante) pode visualizar todos os itens cadastrados no banco de dados. O visual dessa página deve ser, **obrigatoriamente**, uma cópia [desse projeto](https://github.com/bastienwirtz/homer).

**Comment by JeanCHilger** [comment]
@Dovyski, devemos utilizar a dashboard em si, ou apenas seguir o modelo de layout, codificando nós mesmos os estilos?

**Comment by Dovyski** [comment]
Utilizar o dashboard em si (copiado dos os arquivos e estilos para ficar igual). Nesse dashboard, tem um retângulo para cada "Applications". No nosso caso, a única coisa diferente é que cada retêngulo será um item (comentário).

**Comment by JeanCHilger** [comment]
A dashboard utiliza um arquivo estático (`public/homer/assets/config.yml`) para configurações, no entanto a lista de itens é definida neste mesmo arquivo e não há nenhum lugar explicando se é possível utilizar uma URL (com dados retornados de uma API, por exemplo) ou outro arquivo como esta lista. Eu abri uma issue perguntando sobre, vamos esperar para ver como prosseguir, caso não possamos utilizar outra fonte como dados destes itens, talvez tenhamos que achar uma forma de escrever diretamente no arquivo quando a URL é acessada.

**Comment by Dovyski** [comment]
Muito provavelmente o script javascript que carrega o `public/homer/assets/config.yml` pode ser editado para pegarmos os dados da nossa própria API. Podemos remover por completo a dependência para esse `config.yml` e trabalhar apenas com JSON e APIs.
