### ISSUE TITLE
[Dúvida] Dúvidas em relação à issue 41 do programa

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#70]
Tenho algumas dúvidas sobre o comentário do @lcaimi [nesta issue](https://github.com/practice-uffs/programa/issues/41#issuecomment-656131171). Algumas dúvidas são em relação á compreensão outras são em relação à implementação, por isso vou marcar o @Dovyski aqui tbm:

1. Este formulário apareceria depois que um `Serviço` fosse requisitado, ou este form diz respeito a um `Serviço`?
2. Não compreendi o significado dos campos `Tipo`, `Público-alvo` e `Roteiro resumido`, alguem poderia, por gentileza esclarecer isto?
3. Esses campos compreenderiam uma nova entidade (distinta de `Item`) certo? Neste caso qual nome deveríamos "adotar" para ela?
4. Caso este formulário deva ser mostrado quando o usuário for requisitar um serviço, devemos alterar a forma como fazemos agora, utilizando um objeto `Item` para tudo, ou a requisição de um *feedback* seria semelhante?

(PS: desculpas por estar buscando sanar as dúvidas apenas agora, depois de tanto tempo com a issue aberta).

**Comment by Dovyski** [comment]
Essa é uma questão difícil de resolvermos agora. O projeto web-feedback nasceu como um mural de ideias e sugestões, mas a ideia é que ele evolua para uma central do programa.

O que o @lcaimi comentou é o que você entendeu, @JeanCHilger 

> 1. Este formulário apareceria depois que um `Serviço` fosse requisitado, ou este form diz respeito a um `Serviço`?

Esse formulário diz respeito a um serviço. Um serviço é algo que o practice presta para um cliente. Na minha modelagem inicial, eu tinha feito um item ter um tipo `TYPE_SERVICE` para modelarmos tudo de uma forma só. 

Agora eu acho que isso não é mais uma boa ideia. Acho melhyor modelar um serviço como uma nova entidade, e.g. `Service`, que terá vários campos (como tipo, público-alvo). Ainda não sabemos exatamente o que cada um desses campos terá. Por essa razão, vamos tratar todos os campos como sendo textuais (string).

> 2. Não compreendi o significado dos campos `Tipo`, `Público-alvo` e `Roteiro resumido`, alguem poderia, por gentileza esclarecer isto?

São os tipos de serviços que vamos prestar, e quem usará o material produzido. Esse fluxo ainda está sendo definido pelas equipes, então não temos muitas informações no momento. Como eu falei, vamos modelar qualquer coisa nesse sentido como sendo um campo textual no modelo.

> 3. Esses campos compreenderiam uma nova entidade (distinta de `Item`) certo? Neste caso qual nome deveríamos "adotar" para ela?

`Service` seria bem lógico, mas não acho um nome muito bom. Talvez `Product` ou `Order` sejam melhores.

> 4. Caso este formulário deva ser mostrado quando o usuário for requisitar um serviço, devemos alterar a forma como fazemos agora, utilizando um objeto `Item` para tudo, ou a requisição de um _feedback_ seria semelhante?

Vamos separar as coisas, como eu comentei acima. Vamos tratar comentários/feedback como `Item`, e os pedidos dos clientes como outra entidade.

> (PS: desculpas por estar buscando sanar as dúvidas apenas agora, depois de tanto tempo com a issue aberta).

Nada para se desculpar 😉

**Comment by Dovyski** [comment]
Olhar a discussão em https://github.com/practice-uffs/web-feedback/issues/71 para saber do andamento dessa modelagem. Pela minha proposta, não teríamos mais o `Service`/`Product`/`Order`, faríamos tudo no `Item` (com auxílio do `Specification`.

**Comment by JeanCHilger** [comment]
Dado que temos grande parte da discussão resolvida pelo que foi definido na issue #71, irei fechar esta issue
