### ISSUE TITLE
[Engenharia] Definir requisitos de forma mais concreta

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#71]
Como já mencionado, o `web-feedback` é um sistema que está ainda em desenvolvimento, ele nasceu como uma ideia que ainda está em evolução. Esta característica aprensenta a vantagem de podermos moldar algo de acordo com as necessidades emergentes, atendendendo-as de forma mais completa. Todavia, esta maleabilidade torna o desenvolvimento em partes turvo, gerando certa lentidão e retrocesso. Em vista disso, crio esta *issue* para que centralizemos/definamos algumas ideias no intuito de modelar algumas funcionalidades de forma mais concreta.

Qualquer ideia e necessidade deve ser relatada aqui. Quando uma quantidade suficiente for coletada, o @arufonsekun e eu iremos criar as *issues* e desenvolvê-las.

Não há nenhum problema em alterar o *software*, como ocorreu com o `Item`/`Service` - #70 - e com o Homer - #49, apenas acreditamos que centralizando as necessidades e gerando uma espécie de "requisitos funcionais" (de forma nada criteriosa) podemos entregar um produto com maior qualidade e que melhor atenda aos objetivos pelos quais foi concebido.

Para este fim, irei marcar o @Dovyski e o @lcaimi, para que qualquer modificação seja relatada aqui. @arufonsekun e eu também iremos reportar aqui possíveis modificações relevantes que observarmos.

**Comment by JeanCHilger** [comment]
As *issues* #70 e #49 representam as modificações necessárias que temos até então.

**Comment by Dovyski** [comment]
Excelente e muito importante essa issue, @JeanCHilger . Eu vou considerar ela como uma tarefa minha de postar um rascunho geral do sistema com telas em wireframe e um fluxo entre elas. Dessa forma, temos (todos) uma ideia mais geral do sistema e como podemos modelá-lo.

A modelagem atual, que eu fiz, foi realmente rascunhada. Foquei na entrega, não no sistema como uma entidade que evoluirá. Acho que estamos em um ponto crítico do desenvolvimento que precisamos colocarmos todas essas fundações.

**Comment by JeanCHilger** [comment]
Caso precisar de ajuda, pode listar as funcionalidades "*core*" que ainda não estão implementadas (ou as ideias essenciais como um todo), que nós pensamos numa espécie de design de telas e daí vamos ajustando.

**Comment by Dovyski** [comment]
Eu fiz um [documento inicial](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.p) com as telas do web-feedback e a modelagem do banco (atual + próximas mudanças). Deem uma olhada para ver se está claro o suficiente. 

Ainda não coloquei informações sobre para onde os links levam (não sei se precisa, realmente). Vocês podem fazer comentários direto no doc, ou adicionar outros elementos que julagarem pertinentes.

Amanhã eu continuo descrevendo cada uma das coisas, mas a ideia é usar `Item` como base para tudo (ideias dos usuários e pedidos de serviço). A tabela `specifications` teria no campo `data` dados serializados do que um item do tipo `TYPE_SERVICE`  possui. Pendem em um json ali. É "feio"? É, mas funciona maravilhosamente bem para todos os casos diversos e perculiares de cada uma das equipes e serviços do PRACTICE.

**Comment by Dovyski** [comment]
Fiz alterações no [documento](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8e07cf4106_1_0) para refletir a discussão sobre modal. Coloquei algumas mais específicas para mostrar um item que é do tipo ideia e outro do tipo serviço.

Um detalhe: quanto eu falo item do tipo ideia, eu me refiro a qualquer coisa que não seja um serviço (ideia, comentário, crítica, sugestão). O web-feedback é tipo um mural. O único tipo que realmente tem um fluxo próprio é o serviço.

Se todos estiverem de acordo, podemos começar a criar as issues relacionadas.

**Comment by arufonsekun** [comment]
Do meu ponto de vista eu acho que está bem claro, podemos começar a criar as issues.

**Comment by arufonsekun** [comment]
Estou de acordo com essa modelagem, só tenho uma dúvida em relação as **categorias** de um **Item**. 
 - Somente um Item do tipo Ideia poder ter as categorias: ideia, comentário, crítica e sugestão, certo?
 - Os Itens do tipo **Serviço**  terão categorias?

**Comment by Dovyski** [comment]
> * Somente um Item do tipo Ideia poder ter as categorias: ideia, comentário, crítica e sugestão, certo?

Isso.

> * Os Itens do tipo **Serviço**  terão categorias?

Sim, mas isso ainda está em definição. Para não travar o desenvolvimento, podemos criar uma categoria chamada "Serviço genérico" e implementar a lógica de seleção e afins usando ela como dado.

**Comment by arufonsekun** [comment]
Obrigado pelos esclarecimentos, percebi que eu não havia executado uma atualização do _seeder_ das categorias, as informações antigas ajudaram a me confundir.
