### ISSUE TITLE
Dúvida em relação à estrutura do repositório

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#72]
Atualmente há uma pasta `src` e uma pasta `docs`. A pasta `docs` será utilizada para algo (como integração com o *github pages*) ou podemos removê-la e deixar o conteúdo de `src` direto na raiz?

**Comment by Dovyski** [comment]
Podemos remover, não acho que vamos usá-la. Ela é parte do template de repositório que usamos.
