### ISSUE TITLE
Ajustar token do login

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#73]
Caso esteja rodando o projeto pela primeira vez, deverá ajustar o *token* do login uffs, para que funcione de forma esperada. Siga as instruções abaixo para efetuar a alteração corretamente (é necessário ter executado de antemão os passos descritos no README).

1. Abra o arquivo `vendor\ccuffs\auth-iduffs\src\AuthIdUFFS.php`;
2. Vá para a linha 48, no método `getServiceToken()`;
3. Aletere o valor do retorno da função para `eyAidHlwIjogIkpXVCIsICJhbGciOiAiSFMyNTYiIH0.eyAib3RrIjogIjRrZ2N0dHZ2OWk5OWN0cWx2MHJqc3VkY2Y2IiwgInJlYWxtIjogImRjPW9wZW5hbSxkYz1mb3JnZXJvY2ssZGM9b3JnIiwgInNlc3Npb25JZCI6ICJBUUlDNXdNMkxZNFNmY3k1RVlrTHcwMnk5U1M1akVTZ0tyaFpnQXF5T0NxVUkzVS4qQUFKVFNRQUNNREVBQWxOTEFCTTNPREkxTURRME9ERTJNRE15TXpreE16VTVBQUpUTVFBQSoiIH0.JQsjq26NVT5iKWG5ZvOKqy3m_x8XtxN0PvkPAEtix4g`;
4. Pronto!

**Comment by oraphaBorges** [comment]
Segui os passos dessa Issue para poder fazer a autenticação do sistema e não consegui fazer funcionar a conexão com o idUFFS local. Mesmo após trocar o token da aplicação local, ele fica dando como login inválido.

**Comment by andrewmsilva** [comment]
Imagino que este problema não exista mais. Qualquer coisa, é só reabrir a issue.
