### ISSUE TITLE
[Back] Criar entidade specifications

### ISSUE THREAD

**Issue by arufonsekun** [practice-uffs/web-feedback#79]
Para implementar essa _issue_ será preciso criar o model `Specifications` contendo os seguintes campos:
 - `id` : bigIncrements
 - `item_id`: foreignId
 - `content`: text
 - `created_at`: timestamp
 - `deleted_at`: timestamp
 - Também deverá ser implementado o relacionamento 1:1 com o model `Items`;
 - Para mais detalhes verificar _schema_ do banco de dados na issue #78;

**Comment by JeanCHilger** [comment]
Estou trabalhando nesta _issue_, vou apenas esperar as PRs #87 e #88 serem "mergeadas" para encerrá-la. A _issue_ #85 depende desta issue e das mesmas PRs.

**Comment by Dovyski** [comment]
Só um detalhe que o model deve se chamar `Specifications ` (não `Especifications`) 😉

**Comment by JeanCHilger** [comment]
ah sim, nem reparei que estava assim aqui :(
