### ISSUE TITLE
[Arquitetura] Refatorar Models, Views e Controllers

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#85]
O intuito desta _issue_ é elevar a semântica no _backend_.  Itens com um * ao lado representam itens cuja proposta será estudada com mais calma, para averiguar se a mudança a que se refere irá contribuir sem adicionar muita complexidade.

**Modificações**
1. - [ ] Deverão ser criados [*resources*](https://laravel.com/docs/7.x/eloquent-resources) para `Service` e para `Feedback`. Como feito com `Comment`, permitindo utilizar todo o _backend_ de `Item`, modificando apenas alguns campos para uma melhor semântica;
2. - [ ] *Deverão ser criados controllers dinstintos para `Service` e para `Feedback`. Estes controllers não precisam implementar tudo do zero, verificaremos uma possível herança de `ItemController`, reescrevendo apenas o necessário;
3. - [ ] *Deverão ser criadas *views* específicas para `Service` e para `Feedback`. Dado que possuem muitos aspectos semelhantes muitas views serão mantidas as mesmas para ambos, no entanto, caso seja possível criar algumas *views* distintas sem agregar muita complexidade e trabalho, seria uma prática interessante.

**Esclarecimentos**
- Optaremos por chamar (pelo menos internamente) o atual `Item` como `Feedback`, pode ser?;
- A implatanção do item **1.** pode eliminar a necessidade do item **2.**.

**Comment by arufonsekun** [comment]
Achei a proposta interessante, porém o item 2 deixa as coisas um pouco complicadas pra mim em relação aquilo que estou implementando na _issue_ #80, não que a ideia não seja boa, mas acho que talvez podíamos adiar o refactor desse ponto pro futuro quando a gente não tiver muita coisa pra fazer

**Comment by arufonsekun** [comment]
Minha sugestão é que por enquanto usássemos o `ItemController`.  Função dele nesse momento seria retornar as Views relacionadas a `Service` e `Feedback` (baseado em um parâmetro) ou uma view que se adapte as diferenças entre `Service` e `Feedback`.

**Comment by JeanCHilger** [comment]
Sim, a ideia é não complicar. Como dito na última linha, a implementação do item **1.** pode eliminar a necessecisade do item **2.**, o que levaria a usarmos apenas um _controller_. Mas não se preocupe com esta _issue_ por enquanto, apenas após as implementações em curso entrarem em vigor que eu irei me aprofundar nela.

**Comment by arufonsekun** [comment]
Aah entendi, pensei que isso já estava sendo implementado, desculpe pelo mal entendido :sweat_smile:

**Comment by JeanCHilger** [comment]
Nos próximos dias irei finalizar esta issue (acabei tendo alguns problemas na implementação da issue #79, pré-requisito desta - sorry) e  poderemos avançar com demais modificações.
