### ISSUE TITLE
[Dúvida, UI/UX] Troca entre visualizar Ideias e Serviços

### ISSUE THREAD

**Issue by JeanCHilger** [practice-uffs/web-feedback#86]
Nas _issues_ #49 e #76 a "home" foi refeita. Restou apenas uma questão que eu comentei no documento com as telas, mas acabei esquecendo de retomar mais à fundo no desolvimento das _issues_ citadas. Haverão duas "_views_" para a home, uma mostrando ideias e outra mostrando apenas serviços. A minha dúvida é se a aba de serviços deverá estar visível apenas para usuários que sejam membros do PRACTICE ou que tenham criado um serviço, já que serviços ficam visíveis apenas à estes membros. Assim, apenas os serviços que podem ser visualizados pelo usuário logado estariam visíveis nesta aba (membros do PRACTICE veriam todos, e demais usuários veriam apenas serviços criados).

Caso um usuário não tenha criado nenhum serviço, a aba "serviços" ficará vazia, e isto não me parece muito bom. Poderíamos mostrar uma mensagem como "Você ainda não criou nenhum serviço" quando for o caso, mas do ponto de vista de UI/UX acredito que seria melhor remover esta aba quando não houver conteúdo a ser mostrado. Claro esta é apenas minha opinião e eu não tenho experiência nem conhecimento algum em UI/UX, apenas prefiro a ideia de adicionar este dinamismo.

Há um botão para criar serviços na home, que estará visivel à todos os usuários.

Em relação à complexidade, não acho que será adicionada muita, e como vou desenvolver esta parte, já adianto que está ok assim, o prazo não será afetado.

**Comment by arufonsekun** [comment]
Sugeri alguns detalhes de layout na pr #87 que talvez possam ajudar a conduzir nossas ideias. Também não tenho muita noção de interface e usabilidade, mas caso não houver nenhum serviço criado poderíamos mostrar alguma coisa que ajude a pessoa a ter ideias de como criar um serviço, algo parecido com os templates de _issue_ do github.

**Comment by Dovyski** [comment]
Eu expliquei um pouco mais sobre isso no [documento](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit?ts=5f2cc85b#slide=id.g8d48a17757_0_1662), mas vou escrever aqui também. A página que lista serviços (`S001-A`) mostra todos os serviços em andamento (que estão em condução pela equipe do Practice). Como o programa segue a filosofia de trabalho aberto, acho legal mostrar todos os serviços ativos para todos os usuários autenticados. Dessa forma, todos tem uma ideia da carga de trabalho atual e podem relevar se o seu trabalho está levando mais ou menos tempo.

A página que lista os detalhes de um serviço (`I002-A`), essa pode ter o acesso restrito ao autor/solicitante do serviço e equipe Practice. Dessa forma, garantimos privacidade sem perder em transparência.

Sobre UX/UI, eu concordo que uma tela vazia de listagem de serviço não é legal. Podemos adicionar algo como "Você ainda não criou nenhum serviço" e uma ilustração legal, talvez até um pequeno texto explicando o que é pedir um serviço.

**Comment by JeanCHilger** [comment]
Ah, agora eu entendi, irei providenciar as alterações.
