### ISSUE TITLE
Mostrar nome, idUFFS e pequeno avatar de usuários autenticados

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#92]
Conforme as [descrições do sistema](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_993), usuários autenticados em informação do nome, idUFFS e um pequeno avatar no canto superior direito da tela. Isso precisa ser implementado. O avatar pode ser um placeholder qualquer no momento, porque não temos a API para isso.

**Comment by arufonsekun** [comment]
Irei trabalhar nessa issue
