### ISSUE TITLE
Criar item "Ideias" na navbar do site

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#94]
Conforme a [descrição do sistema](https://docs.google.com/presentation/d/1TudkpSbs0534rz1I6b-kGmvhQqnDulYP1d5ehQdHIXE/edit#slide=id.g8d48a17757_0_993), a navbar deve conter um link chamado "Ideias" que vai para página que lista todas as ideias.

Essa página já está implementada, precisamos apenas criar o link.

**Comment by JeanCHilger** [comment]
Esta _issue_ será resolvida em conjunto com a implementação da _issue_ #93.
