### ISSUE TITLE
Mostrar título, autor e reações nos cards de ideias

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#95]
Na página de listagem de ideias, os cards mostram apenas a descrição da ideia. As seguintes informações adicionais precisam ser mostrados:

* [ ] Colocar o título da ideia no topo da card.
* [ ] Nome e avatar do autor da ideia, na parte de baixo da card (conforme a ilustração abaixo):
* [ ] Lista de reações àquela ideia, mostradas abaixo do nome do autor (conforme a ilustração abaixo).

![image](https://user-images.githubusercontent.com/512405/90764935-866ad280-e2bf-11ea-9c07-86801d41ff3a.png)

Como eu acho que a card de ideia e serviço é a mesma, a implementação dessa issue deve provavelmente dar de brinde essas melhorias para as cards de serviços. Se isso não for o caso, não há problema.

**Comment by arufonsekun** [comment]
Irei ficar com essa _issue_
