### ISSUE TITLE
Melhorar ícones das reações

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/web-feedback#96]
Atualmente é possível dar um "thumbs up" e "thumbs down". Porém, precisamos de outras reações. As reações precisam ser alteradas para emojis exatamente na mesma configuração que é utilizada nas issues do github:

![image](https://user-images.githubusercontent.com/512405/90765318-1ad53500-e2c0-11ea-8d60-3e09fb03a5c4.png)

Detalhe que essa minha ilustração está em dark mode porque uso uma extensão, não precisamos usar dark mode no sistema.

**Comment by JeanCHilger** [comment]
Quanto aos ícones a serem utilizados, alguma sugestão de onde poderíamos pegar? Os do _material icons_ são apenas em preto e branco, portanto pensei em utilizar do [flaticon](https://www.flaticon.com/), mas gostaria de saber se não conhecem/preferem outras opções.

**Comment by JeanCHilger** [comment]
Uma solução mais simples seria apenas usar os emojis em formato de texto mesmo,  utilizando o [getemoji](https://getemoji.com/) por exemplo, mas não sei o quão _portable_ essa solução seria. Acredito que um pacote de ícones seria uma solução mais "correta".

**Comment by Dovyski** [comment]
Eu gosto da sugestão do getemoji com emojis em modo texto mesmo (se não me engano, a modelagem do banco de dados já prevê isso). Antes de fazer isso, talvez seja uma boa dar uma olhada nessas duas soluções (open-source e com excelente qualidade/personalidade):

https://openmoji.org/
https://github.com/twitter/twemoji

Eles tem versões em SVG que podemos usar e garantir o mesmo visual, independente de browser/plataforma.
